### ISSUE TITLE
Handling of SIGINT and how to handle server fail

### ISSUE THREAD

**Issue by ribalba** [SocketCluster/socketcluster#109]
Hey,
we are currently running a socketcluter cluster* (with redis for multi machine sync) and I would love to do some cleanup when one of our nodes reboots or dies. The client just reconnects and gets a new socket on a new machine. But the redis/ cache will still hold data for the "old" socket. While we can do this cleanup if the client drops out we can not do this when a server needs rebooting (or even dies). So my questions:

1. Is there a way to figure out all the sockets that are connected to a channel? If we could do this, we could do a cleanup on a new server boot/ or have some sort of gc?

2. Is there some standard way to figure out when a worker gets a sigint? Or should I just use process.on('SIGINT')

Cheers Didi

```* no pun intended ```

**Comment by jondubois** [comment]
@ribalba That is a tricky case, I think one safe solution would be to set an expiry on all temporary socket data - You can keep extending the expiry for each socket's data so long as that socket is connected - You can keep refreshing the expiry at an interval of your choice.

If the server dies, the data will naturally expire without having to clean it up explicitly.
You can listen for a 'SIGINT' in the worker like you sugest but you cannot guarantee that a SIGINT will always happen - If the SC server loses all power suddenly and the socket data is sitting on a different machine, there will be no way to clean it up.

There is no way to easily check which sockets/users are in a particular channel - This is tricky because subscribers of a single channel could be hosted on different processes or machines - It would require an external (distributed) storage solution to allow multiple machines to share that data between all machines. This task is better left to developers.
