### ISSUE TITLE
Connect with Express Server

### ISSUE THREAD

**Issue by ccravens** [SocketCluster/socketcluster#112]
New to SocketCluster and very excited to get this project integrated into a few of our projects! I see that SocketCluster uses "ws" as the WebSocket implementation and is built on top of that. When I use "ws", I connect it to the preexisting express server like so:

	var express = require('express');
	var WebSocketServer = require('ws').Server;

	var app = express();
	var server = app.listen(config.port);

	// This is where I pass the above server object to WS config option
	var wss = new WebSocketServer({server:server});

	wss.on('connection', function(ws) {
		console.log('WS Connected');
		ws.on('message', function(message) {
			console.log('WS Receive: %s', message);
			ws.send('hello from server!');
		});
	});

I did not see if this is possible with SocketCluster as well? Is it possible that SocketCluster could provide a config option of "server", which we pass the Express server object and SocketCluster just passes it directly on to the "ws" server config option? Or must we manually provide a separate port?

**Comment by jondubois** [comment]
@ccravens SC needs to take control of the creation and management of underlying HTTP servers in order to coordinate them across multiple processes.

Express can be setup in two ways; 

- In the example you provided, express is creating the HTTP server internally and then you effectively wrap your WS server around it.
- The other way to achieve the same result is to create the HTTP server explicitly and then attach express to it along with your WS server.

E.g.
```js
  // How to use express with SC
  var app = require('express')();

  var httpServer = worker.httpServer;
  var scServer = worker.scServer;

  // Add middleware to express
  app.use(serveStatic(path.resolve(__dirname, 'public')));

  // Here we are passing express to the HTTP server
  httpServer.on('request', app);
```

Because SC needs to take control of the HTTP server creation step, it favors the second approach - It works well with modular frameworks likes express but it clashes with other frameworks (e.g. https://github.com/hapijs/hapi) which also take control of the http server creation.

You CAN get it SC to work with any framework in theory (including Hapi), but this isn't currently documented (coming soon).

**Comment by ccravens** [comment]
@jondubois The second method you mention worked for me and your explanation here helped clarify for me. Thank you!
