### ISSUE TITLE
Concurrent user limit

### ISSUE THREAD

**Issue by tbashor** [SocketCluster/socketcluster#124]
In the documentation it says that there is a 42K concurrent user limit per server and this is a limitation of the client. For the app I'm working on, the socket client will not be a socketcluster client, but a Xamarin websocket client. I'm assuming that any websocket client can connect to a socketcluster server. Given that assumption, does the 42K limit per server apply?

**Comment by jondubois** [comment]
@tbashor There is no hard client limit per server. You can always add more CPU cores to your server and handle more clients. According to this page http://socketcluster.io/#!/performance, on an 8 core machine, it was still only using less than half the total available CPU with 42K connections. So on an 8 core it could probably handle at least 84K in reality.

In the stress test, the limit wasn't caused by the client code itself, it was the machine which was used to simulate the clients that wasn't powerful enough. The clients were being created by a single 32 CPU core machine and ALL 32 of these cores were being used at 100% capacity so it couldn't create any new clients. This was a limit of the testing environment, not of the SC server.

SC has its own protocol on top of WebSocket - So you would have to follow it if you wanted to build your own client for it.

**Comment by abhi86813** [comment]
I am also unabele to gain more than 4K connection, trying from 1 client or more than 4 clients, result is same for all. Please suggest how to scale on 1 core CPU, more than 4K.

**Comment by jondubois** [comment]
@abhi86813 You need to increase file limits. On Linux there multiple commands that need to be run to increase the limits. Also you need to increase the limits on both the client and server machines (if you're doing a stress test).

https://www.tecmint.com/increase-set-open-file-limits-in-linux/
