### ISSUE TITLE
Server to client public Auth

### ISSUE THREAD

**Issue by roblav96** [SocketCluster/socketcluster#125]
So I'm having a hard time here wrapping my head around this socket cluster. :X

I'd like to have about 1000 different channels with maybe 10 users per channel. My only concern is publishing data from the server to the client. The client will not be emitting data.

How can I authorize who is in each channel and whether they can receive publications?

**Comment by jondubois** [comment]
You need to use middleware for access control. See ```addMiddleware``` method here: http://socketcluster.io/#!/docs/api-scserver

There is a MIDDLEWARE_SUBSCRIBE middleware which you can use to block certain users from subscribing to certain channels and a MIDDLEWARE_PUBLISH_IN line for preventing them from publishing to channels.

If you're sure that you never want to allow clients to publish to channels (only the server), then you can set the ```allowClientPublish``` config option to false. See http://socketcluster.io/#!/docs/api-socketcluster

**Comment by jondubois** [comment]
To publish from the server, you can call ```worker.scServer.global.publish(eventName, data, cb);``` anywhere inside your workers.

**Comment by roblav96** [comment]
I'm toying around with the scServer.MIDDLEWARE_PUBLISH_OUT function and the socket parameter. 

From my understanding, the client side auth system is sort of obsolete because can't the client just spoof the
```
socket.isAuthenticated
```
function?

I'm very familiar with web security fundamentals and token authorization. I think I'm a little confused as to how the flow of everything works. I've been reading all the guides numerous times.

I'd like to see if there's a way where I can encrypt a token on the client each time a publish is made then before the client receives the data, verify its token with the handshake middleware.

Are there any ways to set headers or something on the client?

**Comment by roblav96** [comment]
I laos love how you guys are using RethinkDB in your example app :D

**Comment by jondubois** [comment]
@roblav96 Yes, the client can 'spoof' the isAuthenticated property but that won't change the reality that it doesn't have a token which was signed and encrypted by the server. The isAuthenticated property is the server's way of telling the client that it has received a valid token (which was signed by the server itself). It's JWT token-based authentication.

The security lies in the fact that the client cannot sign and encrypt a fake token because they don't know what the authKey is. If the client tries to send a token which they signed/encrypted themselves using the wrong key, the server wouldn't be able to decrypt it and therefore, it would know that this is not a valid token.

**Comment by roblav96** [comment]
@jondubois Excellent response!

Thank you very much for helping me out here. I've successfully been able to get this working property with my Redis DB.

By playing around with the
```
MIDDLEWARE_PUBLISH_OUT
```
middleware, I've successfully been able to verify whether the client can receive updates.

This is really an amazing framework here. I can't wait to show you all what I've done with it.

Next up is trying to actually scale it :D
