### ISSUE TITLE
Get a list of all subscribers in a channel

### ISSUE THREAD

**Issue by rrigoni** [SocketCluster/socketcluster#133]
Hello, 

Is it possible to get a list of all subscribers in a channel? Like a list of all sockets in a room?
I took a look into the channel.watchers() but its a list of functions and not of subscribers. 

Is there any way to achieve this? If not, I'm planning to write my own code and then send you a pull request. 

Thanks

**Comment by jondubois** [comment]
What you're talking about here is a presence service - This is outside of the immediate scope of SC because there are too many ways to implement this (no one-size fits all).

What if you have multiple SC instances/servers? Then where should you store the the list of socket IDs? You will need to store it in an external service which all your SC instances/servers can share (so the implementation of this feature would be different).

This specific case (for a single-server scenario) might make a good server-side plugin though... Your plugin could attach a new method to the server-side SCSocket object e.g. ```socket.getSubscribedSockets(channelName, callback)``` where callback could be in the form ```callback(err, data)```.

Then if someone needs to scale their app beyond a single server, they could just use a different plugin (maybe one which exposes the same ```getSubscribedSockets``` method that way they won't have to change their code).

**Comment by roblav96** [comment]
What you want to do is cache the users activity to a db (I use redis) and then organize the table how you'd like. I recommend using redis because it has great pub/sub functions.

Here's an example from one of my projects:
```javascript
server.post( '/geo/toggle_active', function ( req, res ) {
	var data = req.body

	// req.xid = the username of the request
	// data.uname = the username the requester would like to toggle from their channel
	redis.sismember( 'groups:' + req.xid, data.uname ).then( function ( doc ) {
		if ( doc == 1 ) {
			redis.srem( 'groups:' + req.xid, data.uname )
			inGroup( false )
		} else {
			redis.sadd( 'groups:' + req.xid, data.uname )
			inGroup( true )
		}
	} )

	var inGroup = function ( bool ) {
		if ( bool == true ) {
			redis.sadd( 'ingroup:' + data.uname, req.xid )
		} else {
			redis.srem( 'ingroup:' + data.uname, req.xid )
		}

		var _data = {}
		_data.xid = req.xid
		_data.uname = data.uname
		_data.data = bool
		redis.publish( 'actives', JSON.stringify( _data ) )
		return res.send( bool )
	}

} )
```
The user requests to toggle another out of their group and now we can access the usernames 'groups' table in redis to get the users in that channel.
