### ISSUE TITLE
Guidelines using socketcluster with pm2 monitoring?

### ISSUE THREAD

**Issue by roblav96** [SocketCluster/socketcluster#134]
So I'm almost ready for production! :D

I've been using pm2 during development with one broker, one worker and pm2 on single node fork mode.

**Does anyone have experience using pm2 with socketcluster?**

I image I would need to leave pm2 in fork mode and let socketcluster organize the clusters on it's own? I'm going to play around with it later on tonight and let everyone know incase they want to use pm2 as well.

**Comment by IngwiePhoenix** [comment]
Hey @roblav96 !

Glad to hear that you are almost ready. In order to help you, I will take excerpts from my own source code. Because, believe it or not, I am doing exactly that already within development in order to make sure that things actually work.

Since I didn't want ot use pm2 for my project, but a simpler project, I coded [PowerHouse](https://github.com/DragonsInn). In it, I can declare two kinds of workers; a child process and a forked process. They do sound similar, don't they?

And that is exactly where I ran against with SocketCluster.

Inside Node, you have two API's to create a new node instance:

- `child_process.fork(script)`: Spawn a **new process** using the specified script.
- `cluster.fork()`: Create a **copy** of the current process and assign it as a child to this one.

This second one is SUPER important. Because if you use the ChildProcess method, `cluster.isMaster()` _will return true in both processes_. Also, within a ChildProcess forked process, the supplied script is the main one. So if it forkes inside there again, that script is always the main entry point.

Now that this is sorted, here are some things that you might want to know:

- SocketCluster uses `child_process.fork` to spawn the worker process manager: https://github.com/SocketCluster/socketcluster/blob/master/lib/workercluster.js#L48
- `cluster.fork` is used inside the manager to spawn the real workers.
- `child_process.fork` is used to spawn the broker process, which ACTUALLY is an nData instance: https://github.com/SocketCluster/ndata/blob/master/index.js#L33

Yeah, that was one dive, right? And the answer?

Launch your SC server as a `child_process.fork` instance.

- The process will think it is it's own, but it is not.
- SocketCluster will work just as expected.
- You can talk to the child using events, just like usual.

You can use the process' `message` event to communicate via JSON. You could also use some kind of RPC library like [hprose](https://github.com/hprose) to share functions, or to control the child process via remotely called functions. Your beer. :)

I never worked with pm2, but what I would suggest you is to make sure that your SC server runs as an isolated process through a ChildProcess fork. You can still use the sc-client or redis events to talk to the cluster - but, that is what I would recommend. In fact, that is exactly what I am doing myself!

To demonstrate:
- Starting:
    * https://github.com/DragonsInn/BIRD3/blob/yii1_to_laravel5/app/bootstrap/nodejs/app.js#L51-L57
    * https://github.com/DragonsInn/BIRD3/blob/yii1_to_laravel5/app/Backend/Service/SocketCluster.js
- Communicating: https://github.com/DragonsInn/BIRD3/blob/yii1_to_laravel5/app/Backend/Communicator.js

Redis acts as a global eventer. SC's broker process is aware of that using the sc-redis stuff. The web server process doesn't really care, since most communication is for backend stuff.

I hope this could give you an idea on hwo to setup your pm2 to properly run SC! :)

**Comment by roblav96** [comment]
woah! Thanks for this amazing batch of help! I'll play around with this and let you know how I make out.

**Comment by Kannaj** [comment]
Hello - is it ok to to use this method for production? According to babel , the module isnt meant for production

https://github.com/babel/example-node-server/issues/13

Is there any other way possible though?
