### ISSUE TITLE
Sticky Processes?

### ISSUE THREAD

**Issue by StevePavlin** [SocketCluster/socketcluster#138]
First of all, great project I'm sure I will use it instead of writing my own horizontally scalable implementation. I'm trying to understand this one part of this package though. In vanilla socket.io, you can implement interprocess communication (not cross server) using this:

https://github.com/indutny/sticky-session

If I use a sticky load balancer such as nginx to load balance between all brokers (servers from what I understand) connected to one redis pub/sub MQ, how does the cluster know which client has previously connected to a certain core and does it connect the client to that core? The sticky session uses an implementation which modulus' the ip address by the number of cores to get a random core that user will constantly connect to given that specific server is chosen by the load balancer.

My question is, how does socketcluster perform this same action?

**Comment by jondubois** [comment]
Unlike Socket.io, SC doesn't need sticky load balancing between workers. The reason is that Socket.io starts with a HTTP polling transport (which involves multiple HTTP requests) and the sticky-session module is necessary to ensure that multiple requests get routed to the same worker process.

SC doesn't use long polling, it's just pure WebSockets, so a single connection is naturally bound to a single process (for the entire life of the connection) - Each WebSocket connection is stateful by default so you don't need session stickiness. The only reason Socket.io needs sticky-session is because it's trying to simulate a stateful protocol (WebSockets) using a stateless protocol (HTTP).

Brokers are there to allow workers to efficiently exchange channel messages with each other (for doing pub/sub - Which is one of the most important features of SC). They can also be hooked into remote message queues so that multiple SC instances can share messages with each other and share the same data channels.

Brokers are launched and managed by SC automatically. You can launch multiple brokers as part of a single SC instance.

Each broker manages (handles message passing for) a subset of all pub/sub channels. So for example, if you have 100 channels and 5 brokers in your system, then each broker will manage 20 channels - So each broker will have less work to do.

Each broker process is independent from one another so they don't share any work with each other (sharded according to a hashing function and based on the channel name) - Each broker manages their own subset of channels - And each of them can hook into a remote MQ and sync their own channels.

**Comment by hustcer** [comment]
@jondubois Shall I use `nginx` for WebSocket proxying to achieve a better performance? Or there is no need to do it?

**Comment by jondubois** [comment]
@hustcer It probably depends on your use case. Based on one of the benchmarks I've seen, nginx was only about 5% faster than Node.js' cluster module - This is not statistically significant.

You may want to use nginx or HAProxy if you want to spread the load across multiple physical hosts but you don't really need if you're running a single host.

**Comment by hustcer** [comment]
@jondubois Ok, Thanks.
