### ISSUE TITLE
Quick question about the new RSA encryption...

### ISSUE THREAD

**Issue by roblav96** [SocketCluster/socketcluster#140]
I'm deploying my socket cluster over https. I'm under the impression that my JWT would be encrypted over that protocol.

What would be a good use case for RSA encryption?

**Comment by jondubois** [comment]
It's recommended to run it over https. In addition to preventing eavesdroppers from seeing your data (including the content of your JWT token), an important case to consider is that some old corporate proxies may block plain WebSocket traffic.

If delivered over SSL/TLS, this doesn't happen because the proxy generally won't be able to tell the difference between WSS or HTTPS traffic (since it's all encrypted).

**Comment by roblav96** [comment]
Interesting. I didn't know corporate proxies did that. Great tip!

I'll be using https://github.com/digitalbazaar/forge as my encryption engine. If you aren't familiar with it, check it out. They've implemented all high level cryptography in native js.

I just discovered the greatness of https://gitter.im/
I do apologize for posting my questions to the repo as issues. I'll stop that and use gitter from now on. 

Do you guys accept donations? I could not find a link. Thank you for the help as always!
