### ISSUE TITLE
best practice for deploying to heroku?

### ISSUE THREAD

**Issue by seiyria** [SocketCluster/socketcluster#144]
If I wanted to deploy a socketcluster instance to heroku, should I scale by heroku dynos, socketcluster workers, or maybe both?

**Comment by jondubois** [comment]
It depends on your scaling strategy and the following factors:

- How difficult it will be for you to scale horizontally (adding more dynos/instances)?
- Messaging patterns in your system; does your system tend to have a lot of one-to-many messaging (I.e. a message from one user might be sent out to hundreds of other users - Reddit style interactions) or are the communications generally one-to-one?

Systems which have one-to-many messaging could be orders of magnitude more efficient when run on a few large machines versus lots of small machines because it reduces bandwidth consumption.

For example, assume a scenario where you have 100 small instances vs 10 big instances and you want to broadcast a single message to everyone across all your instances. In the first case, 100 copies of that message will have to go across the network while in the second case, only 10 will go across the network (it requires only 1/10th of the bandwidth).

**Comment by seiyria** [comment]
It's easy to scale horizontally - `heroku ps:1` (where `1` is the number of dynos, I believe).

From where I stand, one client connects to an instance, and right now there is nothing but that. I plan to eventually have a store or two dedicated to certain bits of data but those will only be for small groups of clients at most.

I think you answered my question though - I'll probably focus on scaling workers first, then dynos if I run into problems. Thanks!
