### ISSUE TITLE
Scaling of socketcluster

### ISSUE THREAD

**Issue by carlmathisen** [SocketCluster/socketcluster#145]
Hi Jonathan,

Thank you for a great product!

I am looking into scaling SC quite a bit, and was wondering if you were willing to share some more regarding your setup in this article: http://socketcluster.io/#!/performance

What software did you use to achieve those numbers, besides running the servers on Amazon?

**Comment by jondubois** [comment]
I used Node.js/SC on the server and I spawned 'virtual users' on a large Amazon EC2 instance with 32 CPU cores. To create virtual users - I just ran socketcluster-client inside Node.js and spawned 32 concurrent Node.js processes - Each hammering the SC server with as many connections as they could (and keeping virtual users connected throughout the whole test).

I used the Node.js ```cluster``` module for spawning the 32 processes but you could also do it with the ```child_process``` module.

I used the ```top``` command for monitoring.

So I didn't use anything fancy but it was pretty easy to put together with just Node.js and a bit of custom code. There are probably better tools which can draw nice graphs and such.

**Comment by jondubois** [comment]
Note that I did some new tests recently with SC v4 and interestingly, I found that as of v4, distribution tends to be uneven between workers when using default settings - This is because SC doesn't use the same default as Node.js for loadbalancing. You can make the distribution more even by changing the ```schedulingPolicy``` setting to ```'rr'``` here: http://socketcluster.io/#!/docs/api-socketcluster

The default schedulingPolicy which SC uses lets the OS decide how to allocate new connections to which worker processes (and the default scheduling algorithm for Linux cares more about raw efficiency than making sure all processes are even). I suspect it's because spreading the load evenly between all processes might not be as efficient (in terms of CPU cache usage) as concentrating the work on as few cores as possible... Just a guess. Maybe it's related to the fact that I was sending exactly the same message string over and over to the server during the test (and so the OS tried to use the CPU cache more?)... Maybe I should send a string of random numbers instead?

The reason why SC uses the default OS scheduler by default is because it has no theoretical scalability limits while using the Node.js scheduler (using ```'rr'``` schedulingPolicy) does - This is because when you use 'rr', a single process will be responsible for accepting ALL new connections (so that process may become a bottleneck is you have like 16 workers or more...). Some people prefer to have even processes in any case for peace of mind - So using 'rr' might be the best solution - You should try both and see which one you feel more comfortable with.

With the default OS-based schedulingPolicy, I got to a point where one worker was close to 100% (while others where like 50% and some were close to 0%). It looks like some workers were almost idle and only started picking up the slack when one of the workers approached 100% - Interestingly enough, I noticed that the process which was close to 100% eventually stopped accepting any new connections - So basically, even though the distribution was uneven, it looked like all clients were getting good service (including the ones attached to the busiest process).

It would be interesting to swap out the default Linux scheduler for another one which puts more value on evenness across all cores (as opposed to raw overall efficiency).

**Comment by carlmathisen** [comment]
Thanks, @jondubois! Very useful information.

**Comment by Kiranshinde5121** [comment]
@jondubois  : Hi can I get the code used for this setup...We have to do stress test of socketcluster...
I am using SocketCluster/sc-stress-tests for testing...
We are able to achieve only 4K concurrent connection on Server, then we are getting socket hung up error.

Our setup : 
worker :1 
broker :1 

1) limits.conf : 
*               soft    nofile          1000001
*               hard    nofile          1000001

2) 20-nproc : 
*             soft    nproc     100000
*             hard    nproc     100000

3) CPU info: 
# lscpu
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                2
On-line CPU(s) list:   0,1
Thread(s) per core:    1
Core(s) per socket:    1
Socket(s):             2
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 60
Model name:            Intel Core Processor (Haswell, no TSX)
Stepping:              1
CPU MHz:               2596.982
BogoMIPS:              5193.96
Hypervisor vendor:     KVM
Virtualization type:   full
L1d cache:             32K
L1i cache:             32K
L2 cache:              4096K
L3 cache:              16384K
NUMA node0 CPU(s):     0,1

++++++++++++++++++++++++++++++++++++

top command result : 
top - 08:43:59 up 1 min,  4 users,  load average: 0.19, 0.07, 0.03
Tasks: 107 total,   2 running, 105 sleeping,   0 stopped,   0 zombie
%Cpu0  :  1.4 us,  0.7 sy,  0.0 ni, 97.3 id,  0.0 wa,  0.0 hi,  0.7 si,  0.0 st
%Cpu1  :  1.7 us,  1.0 sy,  0.0 ni, 97.3 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem :  3881624 total,  3350252 free,   328080 used,   203292 buff/cache
KiB Swap:        0 total,        0 free,        0 used.  3311432 avail Mem 

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                                                                       
 1215 root      20   0 1258172  80884  13172 S   5.6  2.1   0:05.55 node                                                                                          
    3 root      20   0       0      0      0 S   0.3  0.0   0:00.02 ksoftirqd/0                                                                                   
 1112 root      20   0  239788  11212   1136 S   0.3  0.3   0:00.47 supervisord                                                                                   
 1187 root      20   0  977248  25000  12124 S   0.3  0.6   0:00.34 node                                                                                          
    1 root      20   0   43228   3616   2492 S   0.0  0.1   0:01.77 systemd                                                                                       
    2 root      20   0       0      0      0 S   0.0  0.0   0:00.00 kthreadd                                                                                      
    4 root      20   0       0      0      0 S   0.0  0.0   0:00.00 kworker/0:0                                                                                   
    5 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 kworker/0:0H           

++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

This is the client.js file which we are using to generate load :

let argv = require('minimist')(process.argv.slice(2));
let socketClusterClient = require('socketcluster-client');
let cluster = require('cluster');
let os = require('os');
var csv = require("fast-csv");


let testCooldownDelay = Number(argv.cooldown || 5000);

let serverHostname = argv.hostname || '10.139.50.129';
let serverPort = Number(argv.port || 8010);
let numClients = Number(argv.clients || 1000);

// The test type.
let test = argv.test || 'many-subscribers';

let cpuCount = Number(argv.cpus || os.cpus().length);
let numClientsPerCPU = Math.round(numClients / cpuCount);

if (!cluster.isMaster) {

  let workerList = [];
  var workersReadyPromises = [];

  for (let i = 0; i < cpuCount; i++) {
console.log("in for");
    let worker = cluster.fork();
console.log("hiii");
    workerList.push(worker);
    workersReadyPromises.push(
      new Promise((resolve, reject) => {
        worker.once('message', (packet) => {
          if (packet.type == 'success') {
            resolve();
          } else if (packet.type == 'error') {
            reject(new Error(packet.message));
          }
        });
      })
    );
  }

  Promise.all(workersReadyPromises)
  .then((results) => {
    console.log('All clients are connected... Waiting for CPUs to cool down before starting the test.');
    // Wait a bit before starting the test.
    return new Promise((resolve) => {
      setTimeout(() => {
        resolve();
      }, testCooldownDelay);
    });
  })
  .then(() => {
    let deviceID = [];
    let mobileNumber = []; 
    csv
      .fromPath("/home/kiranshinde/socketTest/sc-stress-tests/client/data.csv")
      .on("data", function(data){
      deviceID.push(data[0]);
      mobileNumber.push(data[1])
    })
    .on("end", function(){
       console.log("done"); 
     });

    let counter =0;
   var controlSocket = socketClusterClient.connect({
      hostname: serverHostname,
      port: serverPort,
      multiplex: false
    });
    controlSocket.on('connect', () => {
      console.log("Inside on connect",controlSocket.id);
      controlSocket.emit('onConnect', {
                mobileNo: mobileNumber[counter],
                deviceId: deviceID[counter]
            });
      console.log("counter", counter)
            counter+=1;  
    }) 

    // if (test === 'many-subscribers') {
    //   console.log(`Starting the ${test} test.`);

    //   setInterval(() => {
    //     console.log('Publishing a single message string to the testChannel');
    //     console.log('hi kiran');
    //   }, 1000);
    // }
  })
  .catch((err) => {
    console.log('Failed to setup some workers. ' + err.message);
  });

} else {
      let deviceID = [];
    let mobileNumber = []; 
    csv
      .fromPath("/home/kiranshinde/socketTest/sc-stress-tests/client/data.csv")
      .on("data", function(data){
      deviceID.push(data[0]);
      mobileNumber.push(data[1])
    })
    .on("end", function(){
       console.log("done"); 
     });
    let counter =0;
  for(let k=0; k<cpuCount; k++) {
  let socketList = [];

  for (let i = 0; i < numClientsPerCPU; i++) {
    socketList.push(
      socketClusterClient.connect({
        hostname: serverHostname,
        port: serverPort,
        multiplex: false,
        autoConnect: false
      })
    );
  }
  socketList.forEach((socket) => {
    socket.connect();
      socket.on('connect', () => {
      
      console.log("Inside on connect",socket.id);
      
      /*socket.emit('onConnect', {
                mobileNo: mobileNumber[counter],
                deviceId: deviceID[counter]
            });*/
      counter++;
      
  });

 //socket.disconnect();
	socket.on('disconnect', () => {
	console.log("conn disconnected",socket.id);
    });

      });
/*
socketList.forEach((socket) => {
	socket.disconnect();
	console.log("disconnected :",socket.id);
 })
  */
  if (test === 'many-subscribers') {
    let subscribePromises = [];

    socketList.forEach((socket) => {
      let testChannel = socket.subscribe('testChannel');
      subscribePromises.push(
        new Promise((resolve, reject) => {
          testChannel.once('subscribe', () => {
            testChannel.off('subscribeFail');
            resolve();
          });
          testChannel.once('subscribeFail', (err) => {
            testChannel.off('subscribe');
            reject(err);
          });
        })
      );
    });
    Promise.all(subscribePromises)
    .then((results) => {
      console.log('success');
    })
    .catch((err) => {
      console.log(err.message);
    });
  } else {
    console.error(`No '${test}' test exists`);
  }
}
}
