### ISSUE TITLE
Scaling SocketCluster - Running into problems

### ISSUE THREAD

**Issue by ryanpager** [SocketCluster/socketcluster#161]
Ok -- so this is going to be a little in depth. Currently, our team runs predominantly socket cluster for our socket interface on our live meetings platform. For the most part it works awesome. The current setup is as follows,

AWS ELB (Port 443) => 2 M4.10xLarge EC2 Instances (Port 80)

Broker is just a simple Elasticache Redis instance (top-tier) relay...nothing special.

Workers: 30
Brokers: 10

Nothing else runs on the M4.10xl instances except for the socket server. The instances are run using forever -- and are pretty standard for the most part.

**Problem**

We consistently run live meetings of ~ 200-300 people without any issues at all. I would say even meetings of 1500-1800 are fairly common. There can be upwards of 10k-20k connections at all times. In these circumstances -- its fairly straightforward pub/sub, everything works great.

We recently started opening up a beta for allowing 5k to 7.5k people in a meeting -- and the whole system was crushed. CPU's maxed out at 95% -- the server didnt crash, but there was a huge amount of latency (up to 30s - 1m+ in some cases). In addition -- new connections were refused, and all sorts of other wonky crap happens.

We heatmapped the functions we were running as part of the event cycle -- nothing is blocking, and the event cycles run in < 2ms. It is simply: pull redis object -> update redis object -> put redis object. No database interaction, nothing. Anything writing to a file is done at the end of a meeting -- so nothing ever blocks.

In addition to this, we added 2 extra m4.10xl instances, and the result was the same -- a meeting with 5k+ tapped out the server. We even tried doing 6 c4.8xl instances instead -- same result.

**Questions**

- Is this a known issue -- or am I doing something wrong here?
- Is there some sort of other switch?
- Is there a good way to benchmark this stuff to figure out where the pain points are?

**Comment by jondubois** [comment]
@ryanpager When you say 5k people in a meeting - You mean that some of your pub/sub channels have over 5k concurrent subscribers? How often does the average user send a message to the channel? (On the frontend, does text just stream by really quickly?)

Did you find out what was using up the CPU? Was it Node.js (SocketCluster) or Redis?

Also, do all these 5K subscribers come on all at the same time? Does it always happen or only sometimes?

Based on the last benchmark I did, SC was able to handle 10K concurrent users per CPU core (therefore per channel since each channel can only use a single CPU core) - Each user was sending a message every 5 seconds on average (with some randomization because you don't want all messages to arrive at the same time).

Note that a common problem that might arise when you have a lot of concurrent users is what happens when you restart the server. When you restart the SC server, all clients will be disconnected and they will try to reconnect automatically - If too many clients try to reconnect at the same time, you could get a massive amount of (re)subscribe requests and this could crash the server.
If you look at the autoReconnect options here: http://socketcluster.io/#!/docs/api-socketcluster-client you can specify the randomness in milliseconds (you can make it multiple minutes if you need to).

**Comment by ryanpager** [comment]
@jondubois

Some answers to your questions --

**You mean that some of your pub/sub channels have over 5k concurrent subscribers? How often does the average user send a message to the channel? (On the frontend, does text just stream by really quickly?)**

Yep -- a given channel (in the form of "live-meeting-#{uuid}") can have 5K+ people concurrently. On average an event gets sent every could seconds -- if chat is closed. If chat is open, its pretty standard to have messages flying through at 3-5/sec. We disabled chat on massive meetings because it was making the problem worse (dropped user limit way down) -- but we still could only handle 5K in a channel.

**Did you find out what was using up the CPU? Was it Node.js (SocketCluster) or Redis?**

Redis usage was minimal -- it was 99% SocketCluster.

**Also, do all these 5K subscribers come on all at the same time? Does it always happen or only sometimes?**

We have a lobby where people join when they want for meetings -- so its never all at the same time. Also -- the connections dont seem to be the problem...before the meeting starts and people are just in the lobby with connections -- servers sit at like 1%...no problem. Its when they start shooting off events it becomes an issue.

We have set the auto reconnect options before and it didnt make any difference because of what we were seeing. It was **only** after the meeting started and events start flying through that theres an issue. Once the server starts to choke -- people disconnect/reconnect rapidly which causes issues -- but thats mitigated for the most part.

**Other Questions**

- We are currently on server version 2.3.25... has there been any major performance changes since then? (reading the change logs i dont see anything that jumps out)
- Events are dynamically run in the middleware layer -- an event comes in through ScServer.MIDDLEWARE_PUBLISH_IN, and when it does we match it with a specific function in a separate include, use a require to bring it in, and then run it. Maybe the require is killing it since require is a blocking function?
- Before the event is run, it pulls the "meeting" from redis so it can inject it into the meeting. It shouldnt be a problem, but maybe it is?
- I think our node version is pretty old...could that possibly be an issue?

**Comment by jondubois** [comment]
@ryanpager Do you find that one worker process is doing much more work than the others? Uneven distribution?

There were two big performance optimizations that I can think of since then:

- A 5x to 10x boost in handling new channel subscriptions
- More even distribution of load across worker processes (changed the default schedulingPolicy to 'rr').

Since you have a lot of cores on each machine, you may benefit from an upgrade. But note that there are some breaking changes since then and you will need to upgrade the client too.

Note that if you have some very large channels with 5000+ concurrent users, you might want to to more advanced stuff like "sharding" your channels by (for example) appending an index number at the end of the channel name. So for example if you have a channel "myGroup", you could split it into two channels "myGroup1" and "myGroup2"... Then you can add some randomness on the frontend such that half the time, it will publish the message to myGroup1 and half the time to myGroup2... (You can add a wrapper on the frontend to abstract this).

An SC channel is bound to a single process/CPU-core so if you get too many messages on a single channel, it's possible that one CPU core will reach 100% while the others will stay relatively low. SC is better at handling many small/medium channels than a few large channels. So if you have some really big channels, you may want to split them up into multiple smaller channels.

**Comment by ryanpager** [comment]
@jondubois 

The worker processes are almost bang on evenly split in terms of how much work they are doing. Were going to try doing a few more benchmarks + upgrading our SC library version -- and hopefully that helps.

Thanks for the help -- will update with some findings.

**Comment by ryanpager** [comment]
@jondubois 

Got some good stuff for you --

1. We upgraded finally to the newest version...this significantly helped out distribution of work -- much like you said.
1. We found a big performance hit in our code -- we were doing dynamic requires (why, I have no idea). While node is supposed to cache those requires; it seemed like that was never happening.

**Benchmark Testing:**

1. A new connection was created every 10ms until 2500 connections max were made. We did the test from 2 computers -- so 5000 connections total.
1. After max connections were made, a new event is published every 1000ms
1. Wait for server to die (or keep running)

**Results Before Changes:**

500 connections @ 1 event / sec blew up the server (maxed out 1 thread at 100% cpu usage) -- everyone dropped.

**Results After Changes:**

5000 connections were fine -- it took 5 minutes of slamming the server in order for all clients to get disconnected.

**Note** -- we are recording chat history in a redis object. We completely overlooked that the redis object would grow to massive proportions as you keep spamming the server. This is why each event took more work -- rather than be consistent.

**General Wrap-up / Where Were At:**

- We figured out that things that usually arent a problem are....talk about feeling dumb
- We know that a channel on the new version (4+) will handle easily 5000+ people
- We know that redis, while a great thing -- can be excessively expensive if not done correctly as the record grows.

--

So yea...thanks for the help, I'll continue updating as we figure out more stuff - but getting 10x more stability in a couple days is awesome. The only way well know for certain that this works completely is getting a 5000+ person meeting together...which isnt really an easy task. But this **greatly** helped out.

Thanks, will update soon!

**Comment by scriby** [comment]
Just a random comment on "While node is supposed to cache those requires; it seemed like that was never happening".

Node does employ a module cache (if you require the same file or module multiple times you can verify you get the same object back each time). However, it still does synchronous disk access to resolve the file that is being requested, which is where the performance hit is coming from.

**Comment by happilymarrieddad** [comment]
@ryanpager Are you using a database other than redis anywhere?

**Comment by ryanpager** [comment]
@happilymarrieddad So the issue was with the amount of data we were JSON.stringify'ing and parsing. Our objects were stupidly large (something that happened over time while we were building). We ended up ditching Redis all together and using DynamoDB directly so we could do complex queries -- and the problem went away completely. We are still running into an issue where the max is ~ 10K in a channel, but we might have figured out a way around this.

Really -- this is as resolved as it can get right now, so I am going to close it. Thanks for the help everyone!

/cc @jondubois
