### ISSUE TITLE
node-debug Error: listen EADDRINUSE :::5858

### ISSUE THREAD

**Issue by yandrey** [SocketCluster/socketcluster#171]
Hi,
How to debug sockecluster app? For me node-debug throws  Error: listen EADDRINUSE :::5858 for new SocketCluster, and there is no such exception when " new SocketCluster..." is commented out 

```
'use strict';
var argv = require('minimist')(process.argv.slice(2));
var SocketCluster = require('socketcluster').SocketCluster;

var socketCluster = new SocketCluster({
  workers: Number(argv.w) || 1,
  brokers: Number(argv.b) || 1,
  port: Number(argv.p) || 8084,
  appName: argv.n || null,
  workerController: __dirname + '/worker.js',
  brokerController: __dirname + '/broker.js',
  socketChannelLimit: 1000,
  crashWorkerOnError: argv['auto-reboot'] != false
 });
```
P.S. i tried 
```
SocketCluster({ defaultWorkerDebugPort: 5353, defaultBrokerDebugPort: 6353,  
```
no difference

**Comment by jondubois** [comment]
The instructions are here http://socketcluster.io/#!/docs/debugging

This error means that you already have a process running on that debug port. You should check what t is using ```fuser 5858/tcp``` and then ```kill theprocesspid```. Then run SC again.

**Comment by costa974** [comment]
i'm trying the debugger in visual studio 2015.

but i'm not able to make it work.

Debugger listening on [::]:5858
   [Busy] Launching SocketCluster
Error: listen EADDRINUSE :::5858
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at Agent.Server._listen2 (net.js:1253:14)
    at listen (net.js:1289:10)
    at net.js:1399:9
    at _combinedTickCallback (internal/process/next_tick.js:77:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by jondubois** [comment]
@costa974 Yeah the visual studio debugger doesn't work very well with SC.
Because SC runs as multiple processes, you have to tell it which processes you want to debug. See http://socketcluster.io/#!/docs/debugging

If you use Node.js `v6.4.0` or higher, you can launch Node.js using the command line with an `--inspect-workers` flag - Then you will be able to debug from inside your Chrome browser.

You just have to add `debugger;` statements in your code where you want the debugger to pause.
