### ISSUE TITLE
Errors when create an app

### ISSUE THREAD

**Issue by hopewise** [SocketCluster/socketcluster#173]
I have successfully installed socketcluster via:

```
npm install -g socketcluster
```

however, when I try to create an app, I get this error after creating the files:

> npm WARN socketcluster-sample@1.0.0 No repository field.
> npm WARN socketcluster-sample@1.0.0 No license field.
> npm ERR! Linux 4.1.19-boot2docker
> npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
> npm ERR! node v5.10.1
> npm ERR! npm  v3.8.3
> npm ERR! path ../mime/cli.js
> npm ERR! code EPROTO
> npm ERR! errno -71
> npm ERR! syscall symlink
> 
> npm ERR! EPROTO: protocol error, symlink '../mime/cli.js' -> '/app/myapp/node_modules/.bin/mime'
> npm ERR!
> npm ERR! If you need help, you may report this error at:
> npm ERR!     https://github.com/npm/npm/issues
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     /app/myapp/npm-debug.log
> [Error] Failed to install npm dependencies. Exited with code 185.

Any help is highly appreciated.

**Comment by qLb** [comment]
Don't know what's your env but did you try `--no-bin-links`‎ flag on npm command?                                                                                                                                                                                                                                                                                                                                        qL.b                                                                                                                                                                                                                From: Samir SabriSent: czwartek, 28 kwietnia 2016 12:04To: SocketCluster/socketclusterReply To: SocketCluster/socketclusterSubject: [SocketCluster/socketcluster] Errors when create an app (#173)I have successfully installed socketcluster via:

npm install -g socketcluster


however, when I try to create an app, I get this error after creating the files:


npm WARN socketcluster-sample@1.0.0 No repository field.
npm WARN socketcluster-sample@1.0.0 No license field.
npm ERR! Linux 4.1.19-boot2docker
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v5.10.1
npm ERR! npm  v3.8.3
npm ERR! path ../mime/cli.js
npm ERR! code EPROTO
npm ERR! errno -71
npm ERR! syscall symlink

npm ERR! EPROTO: protocol error, symlink '../mime/cli.js' -> '/app/myapp/node_modules/.bin/mime'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues

npm ERR! Please include the following file with any support request:
npm ERR!     /app/myapp/npm-debug.log
[Error] Failed to install npm dependencies. Exited with code 185.


Any help is highly appreciated.

—You are receiving this because you are subscribed to this thread.Reply to this email directly or view it on GitHub

**Comment by hopewise** [comment]
I tried to as: 

    npm install -g socketcluster --no-bin-links

Then I got this error:

    root@1c35c0f739d0:/app# socketcluster create myapp
    bash: socketcluster: command not found

What would be the full path to socketcluster ? I tried `which `but it didn't return anything..

**Comment by hopewise** [comment]
I tried MEAN stack for bitnami without using docker, I'got no errors, but the server didn't start:

[Success] SocketCluster sample 'C:\Users\Samir Sabri\Documents\npm\socketcluster-master\myapp' was setup successfully.

```
C:\Users\Samir\Documents\npm\socketcluster-master>node server
module.js:341
    throw err;
    ^

Error: Cannot find module 'C:\Users\Samir\Documents\npm\socketcluster-master\server'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:146:18)
    at node.js:404:3
```

How to fix this error?

**Comment by jondubois** [comment]
@hopewise Which version of Node.js are you using? Did you try to ```npm install -g ...``` as as root?

**Comment by amprodes** [comment]
I have the same issue!

**Comment by starrabb1t** [comment]
[Error] Failed to install npm dependencies. Exited with code 243.
while ```socketcluster create```
