### ISSUE TITLE
uWS optimization - prepareMessage

### ISSUE THREAD

**Issue by jondubois** [SocketCluster/socketcluster#180]
To optimize outgoing messages when publishing to a large number of subscriber sockets, we should invoke uWS socket's prepareMessage first (outside of the for loop) and send as as separate step.

Also make sure that higher-level message preparation steps such as JSON.stringify() only happen a single time before sending the same message to multiple sockets.

For example, here we can stringify the packet before entering into the for loop: https://github.com/SocketCluster/sc-broker-cluster/blob/960c147e9a03ad587ae021d5226d52673919557c/index.js#L639-L643

**Comment by kinsi55** [comment]
I know this is rather offtopic but have you ever been able to figure this out? Unfortunately UWS has since been pretty much "deleted" / unsupported thus finding anything on how to properly use this seems like a challenge to me. I've tried to call prepareMessage w/ a Buffer as the first arg and the opCode as the second [Like I was able to find here](https://git.eu-gb.bluemix.net/niels.ten.boom/chatbot-server/blob/8dea86e0bf9f2479dc66c95fee401965377983a0/node_modules/uws/src/addon.h#L377), however I always am returned an empty object. The corresponding `.send` method function header matches the one I see regularly used, so that has me wondering what it might be that I'm doing wrong.
