### ISSUE TITLE
why the socket disconnected ,event handlers still worked,until I call off() unbind them

### ISSUE THREAD

**Issue by micyee** [SocketCluster/socketcluster#187]
**worker.js:**

```
module.exports.run = function (worker) {
    console.log('   >> Worker PID:', process.pid);

    var scServer = worker.scServer;

    scServer.on('connection', function (socket) {

        socket.on('syn', function (data) {
            console.log('id:' + socket.id + 'user:' + data.user + 'sys request');
            socket.emit('res', {
                title: 'test for syn'
            });

            console.log('syn success, closed');
            socket.emit('exit', {
                result: 'syn success'
            });
        });
    });
};
```

**client.js:**
```
var later = require('later');
var SocketClient = require('socketcluster-client');

var synData = function () {
    var socket = SocketClient.connect({
        hostname: '127.0.0.1',
        port: 8000,
        rejectUnauthorized: false
    });

    socket.emit('syn', { user:'tester'});
    socket.on('res', function (data) {
        console.log(socket.id + ' : ' + data.title);
    });

    socket.on('exit', function (data) {
        console.log(socket.id + ' ' + data.result + ', closed');
        //socket.off('res');
        //socket.off('exit');
        socket.disconnect();
    });
};

var sched = later.parse.text('every 5 second');
var t = later.setInterval(function () {
    synData();
}, sched);
```

**server output：**
```
id:dSReBQ8AjSvwYDIPAAAAuser:testersys request
syn success, closed
id:lWL3va-Mp8hcRbd1AAABuser:testersys request
syn success, closed
id:Wk5VEOiP9eWPe1cJAAACuser:testersys request
syn success, closed
```

**client output:**
```
dSReBQ8AjSvwYDIPAAAA : test for syn
dSReBQ8AjSvwYDIPAAAA syn success, closed
lWL3va-Mp8hcRbd1AAAB : test for syn
lWL3va-Mp8hcRbd1AAAB : test for syn  <----- unnormal, when i call off() this will disappear
lWL3va-Mp8hcRbd1AAAB syn success, closed
null syn success, closed     <----- up
Wk5VEOiP9eWPe1cJAAAC : test for syn
Wk5VEOiP9eWPe1cJAAAC : test for syn   <----- up
Wk5VEOiP9eWPe1cJAAAC : test for syn   <----- up
Wk5VEOiP9eWPe1cJAAAC syn success, closed
null syn success, closed   <----- up
null syn success, closed   <----- up
```

when i use socket.io instead or uncomment the two line，the result is normal
Thanks！

**Comment by micyee** [comment]
I know！can not bind the event handler repeatedly. But socket.io don't like this.Do we need update the code fixed it?

**Comment by MegaGM** [comment]
**"why the socket disconnected ,event handlers still worked"**
Because in SocketCluster it's your responsibility to decide whether you still need those handlers or not, I believe. What if a socket will be reconnected soon and you don't want to remove any handlers? There are many scenarios, when you would not want to remove handlers from client sockets just because they were disconnected.

Your `on exit` handler on client side with those two `socket.off('event');` lines seems correct to me, but FYI, there is another way to remove your handlers `on disconnect`. Typically it's not a good choise. But in your particular case, maybe it will be the one.
```js
socket.on('disconnect', function () {
  socket.off('res');
  socket.off('exit');
});
```

**"can not bind the event handler repeatedly"**
I don't know why would you do that..
Anyway, why not? Just `.off` that handler before binding it `.on` again. Is there any errors when you doing it that way?

If something is wrong, in order to get some clue what's going on, you may try to check 
```js
socket.hasListeners('event'); // true or false
socket.listeners('event'); // get array of listeners if there is any or an empty array
```

**p.s. "socket.io this, socket.io that" man, don't compare SocketCluster and Socket.io**
SocketCluster is at entirely different level than Socket.io
> Socket.IO - Enables real-time bidirectional event-based communication.
> SocketCluster - A scalable framework that is designed to scale both vertically across multiple CPU cores and horizontally across multiple machines/instances.

If you completely okay with Socket.io and you don't need features of scalability that SocketCluster proposes you, why wouldn't stop to use a sledgehammer to crack a nut?

I am sorry, I wasn't able not to say this. :sweat_smile:

**Comment by jondubois** [comment]
@micyee - As @MegaGM mentioned, a socket in SocketCluster is still alive even when it is disconnected - By default it will reconnect itself when the internet connection can be reestablished. It doesn't make sense for the handlers to be removed just because the socket is currently disconnected.

**Comment by micyee** [comment]
@MegaGM and @jondubois- thank you for my doubts! i'm  too young too simple, and not well understood the socketcluster.
