### ISSUE TITLE
worker to many broker communication

### ISSUE THREAD

**Issue by naelt** [SocketCluster/socketcluster#189]
First, lot of thanks for this awesome project. 

It is possible to publish from a Worker to an specific Broker in an multi broker environment ?
I will subscribe and publish to the same Broker from the Worker. 
My problem is, the following statements  be applied to different Brokers sometimes:

`socket.exchange.subscribe("some_channel").watch(function (data) { // ... };
 socket.exchange.publish("some_other_channel", { // ... );`

Thank you.

**Comment by jondubois** [comment]
@naelt Why do you need to do that?

To answer your question directly: Yes you can. That is pretty advanced usage though, so be careful.

SC lets you define your own mapping function: see `setMapper(mapper)` here http://socketcluster.io/#!/docs/api-exchange (accessible as `scServer.exchange.setMapper(function (key, method, brokerClientIds) {...});`) - Make sure you invoke it when your instance launches and not after (or else existing channels would get lost - SC does not offer runtime rebalancing of the shards).

The mapping function takes a `key`, a `method` and an array of all available broker `clientIds` as arguments and should return the index of the client which the action should be routed to.

SC's default mapper can be seen here (feel free to copy/modify for your own purposes): https://github.com/SocketCluster/sc-broker-cluster/blob/master/index.js#L447-L478

Also, you may want to use/copy this hashing function here too: https://github.com/SocketCluster/sc-broker-cluster/blob/master/index.js#L412-438

You need to be careful though when you change the mapping/hashing functions - The default ones have been tested and are optimized so that load is distributed evenly between brokers, if you write your own mapper function, it's possible that channel names (for example) will not be evenly distributed.

The best strategy is probably to copy the default mapper and hash functions from https://github.com/SocketCluster/sc-broker-cluster/blob/master/index.js#L412-438 and then customize them to add a few edge cases if necessary.

**Comment by naelt** [comment]
Good answer, thank you! It was interesting for me, how do i communicate with a specific Broker.
The reason is, my Worker subscribe a channel and in the next step (same sequence), he published data to him and wait for response from the Broker (the Broker even communicate per  async RPC with MQ).
But sometimes, as described, subscribing and publishing done in several Broker , which is inappropriate in my use case.

I would solve my use case without `setMapper(mapper)`,  if following would be possible:
`socket.exchange.subscribe('some_channel', **{ foo: 'foo' }**).watch(function() { //... })
broker.on('publish', function (channel, **config**) { //... }`
Beside a channel name, the "publish" handler receive a configuration object after subscribing.

'setMapper' or extend [https://github.com/SocketCluster/sc-broker-cluster/blob/master/index.js#L189-L210](url) is now the question... ?!
