### ISSUE TITLE
Synchronize data between workers

### ISSUE THREAD

**Issue by pleqtron** [SocketCluster/socketcluster#198]
Hey,
im trying to scale our new chat application. Currently the application uses some "global" data objects, arrays to do specific actions or hold histories.
Maybe someone can show me a way to acomplish this with multiple workers. 
My only working version is to use the exchange feature by settings keys and retreivcing them on each worker, before action takes place.

To put it in a nutshell: I want to synchronize some data between different workers.

Any help / hint would be appreciated!

**Comment by MegaGM** [comment]
I hope it'll help you. If it won't, feel free to ask any questions.
https://github.com/SocketCluster/socketcluster/issues/44
p.s. Instead of using Redis or another external tool, you can create some internal SC channels for server-side only, rest the same as in example with Redis.
p.p.s. The issue was discussed long ago and I haven't re-read it.

**Comment by jondubois** [comment]
SC shards data between multiple workers, it doesn't synchronize the data - You'd have to do it yourself. SC always tries to use the most scalable approach and synchronization is not scalable beyond a certain point.
