### ISSUE TITLE
Add the ability to change message in middleware

### ISSUE THREAD

**Issue by ivan1986** [SocketCluster/socketcluster#207]
Now any change req in middleware lost
it may be usefull for change forman and add/remove user data
for example - send adta and userlist in message and in middleware filter by userlist and send to user only data

**Comment by jondubois** [comment]
@ivan1986 You can modify the data object by adding an removing fields - You currently cannot replace it though.

So you can do this:
```
scServer.addMiddleware(scServer.MIDDLEWARE_PUBLISH_IN, function (req, next) {
  req.data.foo = Math.round(Math.random() * 1000);
  next();
});
```

Then if a client publishes like this:
```
socket.publish('sample', {hello: 'world'});
```

If you are subscribed to the 'sample' channel, you will receive a message like:

```
{
  "hello": "world",
  "foo": 658 // The middleware added a random foo property
}
```

A few versions ago, this didn't work for the MIDDLEWARE_PUBLISH_OUT middleware, but if you use a newish version, it should definitely work too. (So this approach should work with every middleware type including MIDDLEWARE_EMIT).

Of course the current approach forces you to publish objects as messages - You can't modify raw strings or numbers directly by reference for example. This is because SC doesn't currently offer an API to replace the default data.

**Comment by jondubois** [comment]
It looks like the behaviour of various middleware is inconsistent when it comes to REPLACING the `req.data object` - The MIDDLEWARE_PUBLISH_IN middleware allows it but not the others.

**Comment by ivan1986** [comment]
Ok, thanks, on 5.0 works

**Comment by jondubois** [comment]
@ivan1986 If you upgrade to socketcluster v5.0.4 - You can now replace the entire `req.data` object inside all realtime middleware.

**Comment by JCMais** [comment]
Just a point, after working on something related, do not mutate the `req.data` inside the `MIDDLEWARE_PUBLISH_OUT` if your intention is to change the data just for this receiving socket.

Looks like the changes are also forwarded to other sockets

**Comment by KristofVD** [comment]
Hi @JCMais , I encountered the same behavior. Did you already found a solution for this ?

**Comment by JCMais** [comment]
@KristofVD nope, I've kept all data change on PUBLISH_IN.
