### ISSUE TITLE
Invalid password was supplied to the broker

### ISSUE THREAD

**Issue by happilymarrieddad** [SocketCluster/socketcluster#225]
I keep getting this error whenever I try to pass a large object from one server to another. The weird part is one of the servers does this all the time with no problems and the other one seems to blow up our staging server every time it sends the same packet.. They are both running socketcluster:5.0.16
![selection_158](https://cloud.githubusercontent.com/assets/6416323/18802913/1d431428-81a9-11e6-8f65-54221933cc6f.png)
![selection_159](https://cloud.githubusercontent.com/assets/6416323/18802915/1d4485e2-81a9-11e6-8b5a-fec9f58e76c3.png)
![selection_160](https://cloud.githubusercontent.com/assets/6416323/18802914/1d43f0d2-81a9-11e6-99b2-f5169e54e3e5.png)

**Comment by happilymarrieddad** [comment]
The one on the left is working great and the one on the right, which by the way is a copy paste from the working one, keeps breaking my staging server lol.

**Comment by happilymarrieddad** [comment]
well I rebuilt the server and now it works great.. no idea why.. thanks!

**Comment by happilymarrieddad** [comment]
It's back again. This is a different case though. Now it seems to do it after the server has been running for maybe 3-4 days. I just reset it and it works great for 3-4 days and starts doing it again. It's not really that big of a deal because it's a staging server but it's still kind of annoying. @jondubois do you know why this may be happening? THanks

**Comment by jondubois** [comment]
@happilymarrieddad Can you give be the version numbers of the following dependencies for your staging env and also your production env (to make sure that they're the same):

- socketcluster-server
- sc-broker

Are you setting a custom `secretKey` or changing it at any point during runtime? (you might want to search through your code for references to `secretKey` - This shouldn't change at runtime - To change it, you should restart your entire SocketCluster instances (all processes).

Basically it means that your worker process has a different `secretKey` from your broker process. The secret key is passed from the master process to all children processes (both workers and brokers).

I sounds like it's caused by:
- The `options.secretKey` (in either master, worker or broker) gets changed in your code somewhere during runtime - And this causes the mismatch. Or;
- For some reason the worker and broker processes have different parent master processes... Maybe a child broker process was left over from a previous deployment and somehow SC thinks it belongs to the current instance. If this error happens again, try killing your worker processes using the `kill` command (based on pid) and see if that solves it, if not, try killing your broker processes (again using the `kill` command and passing the pids) and see if that fixes it.

I will try to reproduce on my end.

**Comment by jondubois** [comment]
@happilymarrieddad A good test to do would be to add a `console.log('SC SECRET KEYS:', command.secretKey, scBroker.secretKey)` on line `187` of `sc-broker/server.js` just above the line `result.error = 'Invalid password was supplied to the broker';` - You should log it when everything is working fine, then wait a few days for the error to show up and check if any of the `secretKey` values have changed since last time (they should never change unless you restart the SC master process).

If one of them did change, it would tell us whether it's the broker or the worker which has he wrong key.

**Comment by happilymarrieddad** [comment]
Ok, I'm pretty sure you are right about the leftover deployment. We're good now. Thanks!

**Comment by jondubois** [comment]
@happilymarrieddad how did you terminate SC though? Maybe there is an issue there... It shouldn't leave behind old processes.
