### ISSUE TITLE
Working with multiples cluster channels

### ISSUE THREAD

**Issue by ivopc** [SocketCluster/socketcluster#229]
I am currently working with multiples clusters and I have a question. When the client subscribe to a channel in worker number 0, and the others clients are in the worker number 1 at the same channel we need to deal with brokers passing worker data 0 to 1 and vice-versa in the server?
I've tested it and seems like the server deal with it passing data to others workers by itself, am I wrong?

**Comment by jondubois** [comment]
@ivopc You're not wrong, SC will automatically pass channel messages across multiple workers on a single host.

**Comment by ivopc** [comment]
That is great. I only will use brokers for scaling horizontally?

**Comment by jondubois** [comment]
@ivopc To scale across multiple hosts, you need to synchronize your brokers using a different system like Redis.

Since recently, we've also introduced a number of components to make it much easier to scale SC horizontally. We call these components SCC; see https://github.com/SocketCluster/socketcluster/blob/master/scc-guide.md
