### ISSUE TITLE
Get express data via socket

### ISSUE THREAD

**Issue by trzyrazyzero** [SocketCluster/socketcluster#233]
Hi, how i can read data when socket connet that i set when you go to specife url?
`app.get('/test', function(req,res) {
        req.socket.data = 'my data';
        res.json({success: true});
    });`
and than in connection:
`scServer.on('connection', function(socket) {
console.log(socket.data);
});`

its that possible? Or its possible to set authdata in httpserver?

**Comment by jondubois** [comment]
On the client side, you can pass custom query parameters:
```
socketCluster.connect({query: {someKey: someValue, anotherKey: anotherValue}});
```

then, from the server-side, you can access those inside the `'connection'` handler using something like:
```
var url = require('url'); // The Node.js core url module

var urlParts = url.parse(socket.request.url, true);
console.log(urlParts.query);
```

**Comment by trzyrazyzero** [comment]
Ye, but i want to use passport.js with http server, so its possible to use setAuthToken in express?

**Comment by jondubois** [comment]
@trzyrazyzero 

The best (and also simplest) way to do authentication in SC over HTTP is by creating and signing a new JWT token from express and sending it to the client-side (as a string in the response); then, once you get that token in the response on the client side, you just need to add it to localStorage under the key `'socketCluster.authToken'` (this is the default key). SC will automatically pick it up from local storage when a new connection is created.

**Comment by trzyrazyzero** [comment]
How i can create and sign new JWT token? And by sending you mean socket.emit with JWT token?

**Comment by jondubois** [comment]
@trzyrazyzero Good question.
You can create the JWT token however you like (so long as it meets JWT specifications). In Node.js, you can use the `jsonwebtoken` module directly: https://www.npmjs.com/package/jsonwebtoken

or for convenience you can also use SC's internal `worker.auth.signToken(...)` function like this:

```javascript

// Sample token data, don't store any sensitive/secret data here
// it will be signed but not encrypted.
  var myTokenData = {
    username: 'bob',
    language: 'English',
    company: 'Google',
    groups: ['engineering', 'science', 'mathematics']
  };

  // worker.options.authKey above is the key which SC uses internally to verify the token.
  worker.auth.signToken(myTokenData, worker.options.authKey, null, function (err, token) {
    // The token variable is the JWT token; you can send this to your frontend however you like (e.g. inside an HTTP response)
    // once it arrives on your frontend, you should add it to localStorage under the key 'socketCluster.authToken'- By
    // doing this, SC will automatically pick up the JWT token when doing its handshake
    console.log('JWT token:', token);
  });
```

**Comment by jondubois** [comment]
@trzyrazyzero You can send the token to your frontend however you like... If you're creating the JWT from inside an express GET route, then you probably want to send it back as part of the HTTP response body - But make sure that you handle the response on your frontend and add your token to localStorage using `localStorage.setItem('socketCluster.authToken', token);`.

**Comment by jondubois** [comment]
Note that `worker.auth` above is just an instance of SC's auth engine - The default being https://github.com/SocketCluster/socketcluster-client/blob/master/lib/auth.js

**Comment by jondubois** [comment]
I've updated the authentication page on the socketcluster.io website to link back to this comment. See https://github.com/SocketCluster/socketcluster/issues/233#issuecomment-254871963

**Comment by jondubois** [comment]
@vaskevich You can bypass it entirely.

Because HTTP-only cookies cannot be explicitly accessed (saved/loaded) on the client-side, they don't fit into SC's standard authentication flow but you can still authenticate sockets at a lower level during the handshake phase.

When using HTTP-based authentication using cookies, you can read the cookie from the HTTP request that is associated with every WebSocket object on the server-side.

You can use the `scServer.MIDDLEWARE_HANDSHAKE_WS` to access the HTTP upgrade request (and read any attached cookies) to determine the authentication state of the socket; from that middleware you can either block the connection or attach custom properties to the `req` object (which you will be able to access later using `socket.request` object); so you can do the authentication yourself without relying on SC's authentication mechanism. The main downside to this approach is that the socket's authentication state cannot change throughout the life of the socket connection; but that limitation is inherent to HTTP cookies and is acceptable for the vast majority of scenarios.

Alternatively you can use the `scServer.MIDDLEWARE_HANDSHAKE_SC` middleware; this is the SC-protocol handshake which happens after the native WebSocket handshake; after the socket has been created; it gives you a bit more flexibility when it comes to sending back things like custom errors.

**Comment by vaskevich** [comment]
Gotcha, thanks for explaining. The issue with authentication state remaining constant during the connection isn't an issue for me.

On the implementation side, would you just recommend setting a custom auth engine that essentially does nothing on the client and server side? Would like to avoid sending/validating JWT tokens if they won't be at all used.

**Comment by jondubois** [comment]
@vaskevich If you don't explicitly create as JWT with `socket.setAuthToken()` or manually add a JWT token inside the default `localStorage` location in `socketCluster.authToken` - Then it's not going to send anything. The JWT is only sent as part of the handshake it it exists and the SC server doesn't care at all if there is never any JWT.

Hypothetically you could swap out auth engines (on both client and server) to handle any kind of token from the client (except those set using HTTP-only cookies because they are intentionally not exposed to the client code).

**Comment by danielwpz** [comment]
what if the client is a non-browser one? lets say it's a nodejs client? How can I do auth since there is no local storage or cookie. Via query params? You think it's a good solution?

**Comment by jondubois** [comment]
@danielwpz If the client is running in an environment which does not support localStorage, it will store it in memory (in a private variable) instead.

The main use case for localStorage is to allow sockets to share authentication tokens for the same app across multiple browser tabs. When running the client in Node.js, you don't need this so the socket just stores the token in its own memory.
