### ISSUE TITLE
Use one version of `async`.

### ISSUE THREAD

**Issue by wtgtybhertgeghgtwtg** [SocketCluster/socketcluster#239]
`socketcluster` and `socketcluster-server` require `async@1.5.0`, while `sc-broker-cluster` requires `@async@2.0.0`.  So multiple versions of `async` are downloaded for `socketcluster`.

**Comment by MegaGM** [comment]
The best option IMO is to get rid of the Async module at all.
It should be _relatively easy_ to rewrite some code in the `socketcluster-*` repositories, since there are just a couple of places, where the Async module is required.

I'd like to mention this issue in the Wishlist topic https://github.com/SocketCluster/socketcluster/issues/202

**Comment by wtgtybhertgeghgtwtg** [comment]
That would require a bit more work. but that may be an option, as well.  Between `socketcluster`, `socketcluster-server`, and `sc-broker-cluster`, only three functions, `applyEachSeries`, `waterfall`, and `parallel`, are used.  I had taken a look at that a while ago, and it seemed that the functions could be optimized for their specific uses, as well.

**Comment by jondubois** [comment]
I've updated async to v2.0.0 in socketcluster-server v5.1.6 so that it matches the one in sc-broker-cluster.
We could switch to using Promises instead of the async module but as @wtgtybhertgeghgtwtg mentioned, it would be a fair bit of work (but mostly, we risk breaking things). Particularly the `async.applyEachSeries` function which is used for running middleware in series asynchronously.

We could revisit this at some point in the future, but I don't want to take any big risks since a lot of people are using SC now and it's extremely easy to break stuff.

**Comment by MegaGM** [comment]
Above all, stability, I agree.
Nevertheless, one day, for the sake of posterity, all the code will be rewrited in ES2015 or maybe ES2030 :dancer: 
That day we'll change the Async in favor to Promises or something else anyway.
I'm patient and I'm looking forward for that day. ![](http://smayly.ru/gallery/anime/RedFox/34.gif)

**Comment by happilymarrieddad** [comment]
We are using SC for production and would really appreciate some caution on rewrites lol. Our customers are extremely sensitive and a massive break could cost us a lot of money. Thanks!

**Comment by MegaGM** [comment]
@happilymarrieddad You are programmer, right? You must know - no one will force you to update SC to a next major version, when it will be rewrited.
Furthermore, I doubt it will be soon. Not in next two years, I guess. So, don't worry.

**Comment by jondubois** [comment]
I think the word 'rewrite' is confusing - I don't think SC will ever be 'rewritten'. But small parts might be refactored over time yes.

I think refactoring SC to use Promises instead of async is currently very low priority (unless someone finds an actual bug with it).

In either case, we're at a stage that we probably shouldn't change anything unless we have tests around it (so we can make sure that we don't break stuff).

**Comment by wtgtybhertgeghgtwtg** [comment]
There are a good number of things that can be done if `socketcluster` bumps the minimum `node` version to 4.  It might be enough to warrant a full rewrite.
