### ISSUE TITLE
Hot reload workers.

### ISSUE THREAD

**Issue by wtgtybhertgeghgtwtg** [SocketCluster/socketcluster#241]
Since workers are from a [dynamic require](https://github.com/SocketCluster/socketcluster/blob/42ef1e90123d2d7c0a1ca6fba2ba040beb365862/lib/scworker.js#L272), would there be a simple way to reboot the workers when the file at `appWorkerControllerPath` changes so they run the latest worker?

**Comment by happilymarrieddad** [comment]
++++ this!!!!

**Comment by jondubois** [comment]
We could create a plugin which does that and then add it to the sample/boilerplate by default https://github.com/SocketCluster/socketcluster/blob/master/sample/server.js - We still want to allow the user to remove it in case they want to use a custom hot module loader (and/or transpiler) like babel instead.

It's not as simple as just watching the worker.js file though; we have to watch all dependencies too.

**Comment by wmertens** [comment]
I made a custom listener for passing hot reload events via childprocess messages, it turned out to be very simple. https://github.com/ericclemmons/start-server-webpack-plugin/blob/use-the-fork/src/monitor.js

I also use socketcluster, but in development I use a stub that runs the worker directly, so the monitor hot reloads the worker.

I just now noticed that SC handles SIGUSR2 to restart workers, and start-server-webpack-plugin (v2, not the branch I linked above) can send SIGUSR2 events on module rebuild events, so SC could instead send a message to the worker to handle the hot reload.

Note that SIGUSR2 doesn't seem to exist on windows, so instead SC could just have code like this in the server

```js
if (module.hot) {
  module.hot.accept(pathToWorker, () => sendHotReloadToWorker())
}
```

and on receiving the hot reload message, handle it as in the monitor I linked above.

(For that to work, the file handling `module.hot` must be part of the bundle generated by webpack)
