### ISSUE TITLE
Send persisted notification to new users

### ISSUE THREAD

**Issue by ayush-srtv** [SocketCluster/socketcluster#258]
Hi,
We have a scenario where we'd like to have new user's to our application see some predefined notifications, e.g. some welcome message, t&c etc. How could we go about implementing this with SocketCluster in a way that we pin some notifications with a channel and new users get them delievered when they login the first time.

On a related note, we are also exploring the possibility of having some sort of expiration time with notifications, so that instead of being published and delivered in real time, they are available in the channels till the time they expire. This should allow us to implement the above scenario too by having a potentially large expiry period.

Thanks

**Comment by FantomHD** [comment]
Why not have the server send the client data about the notification and when it expires then have the client handle the rest? Such as it checking to see if the notification is passed expiration, and how to handle it. I don't know about 'pinning' something to a channel, because that doesn't really make sense, seems like it would just me handier to on log in check and see if the person is a new user, if so send them some data, whether through a channel or socket it wont matter.
