### ISSUE TITLE
Send data to all connected clients and specific clients?

### ISSUE THREAD

**Issue by FantomHD** [SocketCluster/socketcluster#260]
Hi there, I'm back again lol.

On socket.io they had the functionality of io.emit (as opposed to socket.emit) which allowed you to emit something to all connected clients. Does socketclusters have this functionality or should I use a channel that all clients are subscribed to when they connect? My only gripe against using a channel is that clients can send data to a channel which opens security holes for what I need to use it for. It should really only be one way from server->all clients.

Follow up, socket.io also had the functionality of io.to(socket.id).emit(), which allowed to me to emit to a singular person. The system I had setup was when they connected, i would save their socket.id in a db attached to another ID i had and later on I would pull their socket.id to send to a specific player without them actually emitting anything for me to reply to. Is this possible as well? 

Thanks for your time, again!

Edit: Also if there is a way to emit to all connected clients, (or even if I am using a channel to do it) will it only contact players who are connected to that worker file, or all players overall. This is something I don't understand about how socketclusters works. I know if I launch more workers, its the equivalent of running 3 diff instances and the load balancer moves clients around between them. However, are all these clients still connected on some level or are all 3 running separate instances of the same app? For example if it was a chat room and I had 3 workers. If 100 people were logged on, would each client see that there was 100 people on line or 33 people online (since the load balancer splits up the connections per worker)?

**Comment by jondubois** [comment]
@FantomHD Yes you should setup a channel to send events to all users. To prevent clients from publishing to that channel, you can either:

- Set the main server-side `allowClientPublish` option to false. See http://socketcluster.io/#!/docs/api-socketcluster - This will prevent clients from publishing to any channel - Only the server will be able to publish to channels.
- Add a MIDDLEWARE_PUBLISH_IN middleware function to block all inbound messages to a specific channel (based on the channel name). See http://socketcluster.io/#!/docs/middleware-and-authorization

Middleware functions are only applied to messages which come from outside (I.e. from clients). So you will still be able to publish from the server-side using `worker.exchange.publish('some-channel', 123)`.

To send stuff to specific users, you can just setup a unique channel for each user. E.g. 'bob-channel' - Then you can publish to that channel from the server-side. One advantage of this approach is that even if the user has multiple tabs open, they will get the message on all tabs that are subscribed - So it's not coupled to a single socketId.

If you want to make sure that a user has received a message, on the server-side, you can create temporary response channels which users can publish to (assuming that `allowClientPublish` is not false). SC is very efficient at creating and destoroying channels. It's OK to have 100 channels per user for example.

**Comment by FantomHD** [comment]
Great! That asnwers all of my concerns! Thanks for adding that bit about how sc can handle plenty of channels too! I would have worried about that later on. I don't know if you caught my edit about how sc handles multiple workers and all the connected clients?

**Comment by FantomHD** [comment]
Also, instead of making another issue ill piggy back here. So the passport fix works great, for now. I realized there was an issue that I will eventually have to address, so I might as well do it now. So with passport, it has its own cookie that it saves and checks for when a player opens a part of my site, to see if they are authorized to be on that site. Now in the past, since my passport cookie and the cookie I used to get their information from was the same thing, I had no issues. But now, since I have 2 cookies saved, one from passport, which it uses to check if im signed in with steam still, and one from sc that takes that same passport cookie data and saves it as another cookie, except signed through sc. Now if i delete that cookie and refresh the page, the page will refresh because Im still signed in on passport with all the right data, but the sc cookie is gone so i dont have any information about who the server is talking to now. In the past this wasnt an issue because if you deleted the passport cookie, you couldnt refresh the page since you were no longer logged in. Now I assume I could use authorization here to check if they still have this cookie and it is all the correct stuff, however this seems redundant as passport already does the same exact thing. Is there anyway I can merge these cookies? Passport's cookie is set through a session with a secret and such, would that work as sc token? 

I tried moving the signing of the token into the passport serialization function then sending back the passport cookie for the server to check, but i didnt work, i assume because the passport key already has been signed with the session secret I set. Any ideas? This is where i moved it, 

`	passport.serializeUser(function(user, done) {
		worker.auth.signToken(user, worker.options.authKey, null, function (err, token) {
			done(null, token);
		});
	});`

**Comment by jondubois** [comment]
I don't know enough about passport's cookie format to give you specific advice. If the passport cookie is a JWT (which I think is not the case), then you could reuse the same token for both passport/HTTP AND SC - You would just have to make sure that the same `authKey` is used for both HTTP/passport and WebSockets/SC and both would be able to read the same token.

If the passport cookie is a session ID and only passport knows about this session, then you can't really combine the two tokens into one - You'll just have to handle them separately - Or change passport for another JWT-based solution. For AngularJS (v1) there is Satellizer - Maybe there are better ones now for other frameworks (or standalone)... I haven't kept track.

Unfortunately, whenever you offload responsibility for tracking authentication to a single process on a single server (which seems to be the passport approach), then it makes scalability difficult - You end up having to store temporary session credentials in a DB/memory store (and you have to remember to clean it up when the user logs out or loses the connection; things get messy/complicated).

JWT is nice because you just sign it once and give it to the client and you don't have to manage it on the backend. It's like an access card - If the user has the card, they can get into the building and enter whatever rooms (open whatever doors) the card allows.

The passport approach is like making every door in a building a smart door with its own WiFi - The user gives the door their personal pin number and then the door has to talk to a central server and check if that user has access to that room. If you have a building with a lot of doors and a lot of users, it becomes really messy (and slows down the network).

**Comment by FantomHD** [comment]
Yea, it seems like I will just have to deal with them separately. To make sure when a user connects that their sc token is authentic and correct, how should I go about that? The console throws an error when the cookie is deleted  but doesn't actually stop it from connecting. How can I verify this token is legit? I assume I have to add a handshake middleware that checks something about the key? Would a property from the key that remains static work as a check to see or is that too risky?

**Comment by jondubois** [comment]
@FantomHD If you have clients who are subscribed to the same channel but connected to different workers, and you publish a message to that channel; all clients (on all workers) will receive the message.

That's what broker processes do; they broker messages between pub/sub channels sitting on different workers. If you use SCC (Kubernetes), then pub/sub channels will even span multiple hosts/machines.

The limitation of SC (and, in fact, all distributed systems) is that you cannot have ALL your user data in one place at the same time. You have to learn to deal with partial data - Pub/sub channels are a really good way to deal with this limitation of distributed systems because it allows machines and users to easily communicate with one another across process and host boundaries.

Using channels, you never have to think about where your users are (I.e. which hosts/processes they're connected to or what their socket IDs are) - You just blindly publish data to channels and let SC deliver the data to the appropriate users (wherever they are).

**Comment by FantomHD** [comment]
Alright! Cannot thank you enough for the well written and thorough responses! My life will be busy and hectic for the next few weeks so I wont get much time to start moving over and transitioning to SC but i think this sums up most everything a quick google couldn't solve for me! Ill close the issue now and hopefully - but for some reason I doubt it! - this will be the last time I have to open a new one.
