### ISSUE TITLE
Passport not recognizing session as authorized only when multiple workers

### ISSUE THREAD

**Issue by FantomHD** [SocketCluster/socketcluster#263]
Hi I'm back ONE last time!! I've successful moved everything over to sc and changed everything that needs to be changed to pub/sub channels. However, I've encountered an error that I simply cannot solve. I spent the past day googling and trying things to fix it before making another issue, but I simply couldn't get it. The system I had worked out was great until I started more than 1 worker. It seems like passport isnt succesfully latching the user data to the session through the serialize/deserialize funcitons (I cant remember which one does that rn)

Here is how the passport workflow should go (I can link to a better visual one if you need it): 

User goes to homepage, the app checks if they are authenticated (by checking if req.user exists or not) if not, it sends them to steam, you login on steam, if it fails you are taken right back to the steam page to relogin (which is what happens every time I log in with more than 1 worker), if it's successful it runs the serialize function then takes you to url/steam/return, there another cookie is set so i can utilize it from socket clusters, and then its redirected to the homepage now successfully authenticated and the deserialize function runs in between one of these last few steps. 

This works great when it's just one worker, but as soon as I start 2 workers it stops working. Where it stops working is when they go to steam to login, afters successfully logging in, the session is serialized, but the user is still sent back to the failure url. I know this is half a passport issue and not really your domain, but its also half a socket clusters issue because it only happens when multiple workers exist.

I can get around this SOMETIMES, its hardly reproducible, by deleting the session cookie while on the steam login page, right before I log in. But sometimes this doesn't work, and when I launch 4 workers, it never works. 

Here is my code, any help or advice you can give is greatly appreciated, but I understand if this simply isn't your alley. 

```
var app = express();

var httpServer = worker.httpServer;
var io = worker.scServer;

healthChecker.attach(worker, app);	 
httpServer.on('request', app);

passport.serializeUser(function(user, done) {
	console.log(user.id + ' serialize');
	done(null, user);
});

passport.deserializeUser(function(user, done) { 
	console.log('DESERIALIZE');
	done(null, user); 
});

passport.use(new SteamStrategy({
	returnURL: 'http://1xxxxxx/auth/steam/return',
	realm: 'http://xxxxxx/',
	apiKey: 'xxxxxxxxxxxxxxxxxxxxxxxxxx'},
	function(identifier, profile, done) {
		process.nextTick(function (){
			return done(null, profile);
		});
	}
));

app.use(session({
	secret: 'secret',
	resave: true,
	saveUninitialized: true,
}));

app.use(passport.initialize());
app.use(passport.session());

app.use('/public', express.static('public'));

app.get('/auth/steam', passport.authenticate('steam', {failureRedirect: '/login'}), function(req, res) {});

app.get('/auth/steam/return', passport.authenticate('steam', { failureRedirect: '/' }), function(req, res) {
	var cookie = {
		'id':req.user.id,
		'displayName':req.user.displayName
	};
	worker.auth.signToken(cookie, worker.options.authKey, null, function (err, token) {
		res.cookie('GameID', token);
		res.redirect('/'); 
	});
});

app.get('/login', function(req, res){});

app.get('/', ensureAuthenticated, function (req, res) {
	res.sendFile(__dirname + '/public/index.html');
});

function ensureAuthenticated(req, res, next) {
	console.log("checking Auth");
	if (req.user){ 
		return next();
	} else {
		res.redirect('/auth/steam');
	}
}
```

**Comment by jondubois** [comment]
@FantomHD That's because passport isn't designed to scale across multiple processes/servers by default.

I can think of two options:
- Use a JWT solution instead of passport for authentication over HTTP.
- Store the passport session data in an external process (e.g. Redis) instead of storing it in memory.

Each worker process has independent memory so if you store data in one worker, it will now show up in the other worker - Data that you need to share between multiple workers needs to be stored in a database/datastore.

Or maybe there is a way to make passport work better with JWT.

This articles says that you can set the session feature to false: https://blog.hyphe.me/token-based-authentication-with-node/

I found this article about storing password sessions in Redis: https://blog.risingstack.com/node-hero-node-js-authentication-passport-js/

The ideal way would be to not store any session data on the backend (just use the signed JWT token for all your authentication needs) - That is the simplest and most scalable approach by far - But if passport doesn't allow you to use that approach, then you may have to use Redis. Or maybe you can find another way to to steam authentication without using passport at all (just handle it yourself inside express and create the JWT token yourself).

**Comment by FantomHD** [comment]
Okay, I'm switching to using JWT to authenticate. How can I verify the sc token I set earlier with jwt? 

I have this to sign the token i pull from socket.authToken:

```
worker.auth.signToken(cookie, worker.options.authKey, null, function (err, token) {
		res.cookie('GameID', token);
		res.redirect('/'); 
	});
```

inside my ensure authenticated function, im trying to use jwt to verify that cookie, how can I go about that? Or do I have to set a whole other cookie for this?

**Comment by FantomHD** [comment]
never mind. I had this: jwt.verify(req.cookies.GameID, worker.options.authKey, function(err, cookie){} to try and verify the token and it didn't work the first time, but now it does. So i guess that's it! This was super simple, dunno why i didn't use this to begin with. Now inside of my ensureAuthenticated instead of checking if req.user exists I just check if this cookie is legit lol.

**Comment by jondubois** [comment]
Yep, or you can also use `worker.auth.verifyToken(signedToken, key, options, callback)` if you want to be consistent. https://github.com/SocketCluster/sc-auth/blob/master/index.js#L9
