### ISSUE TITLE
[Q] Slow performance with uws engine (?)

### ISSUE THREAD

**Issue by pataiadam** [SocketCluster/socketcluster#265]
Hi,

I am trying to build a simple stress testing app to see how fast the uws engine. 
I've created a repository: https://github.com/pataiadam/socketcluster-stress

**The app is very simple**: 
client sends 'event' to the server, and server replies to the client, and the client shows how many messages were delivered in 1 second.

**TL;DR**
With `uws` we got ~5000 msg/sec, but when we use `ws` the number is >11000 msg/sec.  
Why? Maybe I've just forgot something

Thanks :)

**Comment by jondubois** [comment]
@pataiadam I ran your test on a Linux machine and uws was like 4500 messages per second and ws showed less than 1000 messages per second.

But note that these numbers are not accurate because you shouldn't run both the client and the server on the same machine when doing benchmarks. Client sockets use up much more CPU than server sockets so the client will be the bottleneck (which will skew results).

I was able to get over 20K messages per second (with responses) with uws last time I tested and only 10K m/s with ws. Things may have changed since then, but if anything, uws should be even faster now than it was before because the author has kept optimizing it.

**Comment by pataiadam** [comment]
@jondubois Thank you for your answer :)

I also use Linux and run the client on a different machine (both machines (server, client) have i5-3470 CPU @ 3.20GHz)

And an other issue:
I've updated my code: now client is logging the ratio between emitted/published and received message(P/R) (server will reply if it got a msg from client, so P/R should be ~1.0)

(the client and server are on different machine:)
with **ws**:

```
==================
|=|  TC/MC: 1000/1000
|=|  msgPublished: 213000
|=|  msgReceived: 212932
|=|  P/R: 1.0003193507786523
|=|  msg/sec: 12832.640269993371
==================
```

with **uws**:

```
==================
|=|  TC/MC: 1000/1000
|=|  msgPublished: 219000
|=|  msgReceived: 103204
|=|  P/R: 2.1220107747761716
|=|  msg/sec: 5204.700186595391
==================
```

So client "received" the half of the messages when I use uws instead of ws (?)

> I was able to get over 20K messages per second (with responses) with uws last time I tested and only 10K m/s with ws.

Could you share your benchmark code?

**Comment by pataiadam** [comment]
> There may be other issues in your code though because uws should be always be faster regardless.

Probably there are some problem with my code, but I can't see what is the problem. (I've used the sample app of this repository as a base).
