### ISSUE TITLE
Question about manual horizontal scaling

### ISSUE THREAD

**Issue by trakout** [SocketCluster/socketcluster#266]
The documentation states:

> Whenever you receive some channel data from your MQ client, you call broker.publish(channelName, data)

I can see from the sc-redis code that this is indeed happening (`broker.publish(channel, data);`).
However my question is, what happens then? Where does this publish() go?

From the broker API documentation for .publish() (http://socketcluster.io/#!/docs/api-broker):
> Because this method publishes data directly from the broker itself, the broker will not emit a 'publish' event - The 'publish' event only gets emitted when a worker publishes data.

So it doesn't emit a publish event. Meaning, there's no way for a worker to capture this? How does the worker know something has been published in this case? How do I know something has been published by the broker, or, how would I extract information about this publish event and send it to a connected client? 

Does the worker need to be subscribed to the channel before-hand using Exchange? (I've tried using Exchange's .watch() on matching channels with no luck.)

**Comment by jondubois** [comment]
@trakout You need to use `worker.exchange.subscribe('channelName').watch(handlerFunction)` to subscribe to and consume the channel messages from inside worker.js. The Exchange object is basically a special client which you can use to publish and subscribe to channels from the back end (the API is similar to the client socket on the front end).

Every channel in an SC instance is automatically available across all of its worker processes - This is because SC broker processes route and relay channel messages between different workers.

The broker controller (broker.js) allows you to take that concept further and relay channel messages across remote hosts too. So if you hook your local SC brokers (broker.js) to Redis or another remote broker, then you end up with two layers of brokers; one local layer (your SC brokers) which shares messages between worker processes on the same host and one remote one (e.g. Redis) which shares messages between different hosts.

This 2-layer approach minimizes the number of messages that need to pass through the network.
Instead of each worker process consuming messages directly from Redis over the network (potentially with a lot of duplicate messages); it just receives each unique message once from Redis and then shares it across all interested workers on that host only. So the brokers act like a message cache for the host.

The end result is that if you publish a message to any channel from anywhere inside SC, it will reach not only all workers on the current host, but also all workers on all remote hosts which are hooked to Redis  (and all their subscribed end-clients too).

**Comment by trakout** [comment]
@jondubois `worker.exchange.subscribe().watch()` was the missing key. I'm using dynamically created channels (created on socket connection within the worker), and I've got a 'listener' channel at the redis level that announces new channels for redis to subscribe to. I've simply been missing a similar mechanism at the broker <-> worker level.

Thanks for the prompt response!
