### ISSUE TITLE
SocketProtocolError Error handler

### ISSUE THREAD

**Issue by ddolheguy** [SocketCluster/socketcluster#280]
Ive got a React Native app and very occasionally the client is throwing a "SocketProtocolError" which is crashing the app since it's unhandled.

I understand this error occurs when the connection can fail (like over 3G, etc) so I'm not too worried about it but I want to stop the crash and handle the error and attempt to reconnect.

**Comment by ddolheguy** [comment]
Anyone?  Just to add, I also get the "Socket, Hung up" errors too.

Again this request is more about he ability to handle them than resolve them.

Any ideas how?   Please?

**Comment by happilymarrieddad** [comment]
Hey Man, 

I'm not too sure what you're asking for but here is the documentation on client-side connections including error handling. 

http://socketcluster.io/#!/docs/api-scsocket-client
https://github.com/SocketCluster/sc-errors/blob/master/index.js

I would suggest doing something like

socket.on('error',err => {
  // Do something amazing!
})

I hope this helps!

**Comment by ddolheguy** [comment]
Thanks but unfortunately that doesn't cravat he the error as I'm already doing this.

The error itself is really rare, like we have probably 1k plus connections per day and we see 2-3 errors per day.  I'm guessing it's because the client gets an unknown error code or message from the server.   I only ask as I'm looking for more of a global wrapper but the connection on error you referenced too doesn't seem to catch this.

**Comment by happilymarrieddad** [comment]
Have you tried listening for errors on the process like
process.on('exit')
process.on('error')

**Comment by jondubois** [comment]
@ddolheguy As you suggest, these are exceptions more than errors so they are bound to happen from time to time because of bad connections.

Do you mean error handling on the client side or the server side?

On the client side, you just need to attach a `socket.on('error', function() {/*handle error here*/});` handler to prevent the error from being uncaught (and crashing the app).

On the server-side, you shouldn't have to handle it explicitly - Socket errors are scoped to the socket and so should not crash the server.

You shouldn't explicitly have to reconnect since SC will try to auto-reconnect by default.
