### ISSUE TITLE
Allow for a person to subscribe to multiple channels at once

### ISSUE THREAD

**Issue by JGreenberger** [SocketCluster/socketcluster#282]
A user should be able to subscribe to an array of channels at once.   

I noticed in the website sample (https://github.com/SocketCluster/socketcluster-website/blob/master/public/assets/js/app.js), it is subscribing to each channel individually.  This is cumbersome is you are trying to subscribe to 500 channels at once.  A person would have to loop through each one. 

Proposal: 
socket.subscribe(['foo', 'bar']);

**Comment by BojDom** [comment]
Why this is ignored?
Also will be nice ti have something like socket.subscribe('mychannel/*')

**Comment by jondubois** [comment]
@BojDom @JGreenberger Sorry for not making a comment sooner, this feature is already supported! Has been since version 8 so make sure that you use the latest socketcluster and socketcluster-client versions.

To use it, all you have to do is pass a `batch: true` option when subscribing to a channel.
E.g:

```
let myChannel1 = socket.subscribe('myChannel1', {batch: true});
let myChannel2 = socket.subscribe('myChannel2', {batch: true});
...
```

What that means is that the subscribe actions will only occur on the next tick. You can subscribe to a large number of channels in a `for` loop and all the subscriptions will be sent as a single websocket frame.

**Comment by jondubois** [comment]
@BojDom Regarding your suggestion with wildcards, there are no plans for this because pattern matching adds complexity and isn't great for performance.

You can implement it yourself in SC though if you feel that it's important (it shouldn't be too difficult) but my initial thought about it was that I didn't want to encourage this use case too much because of performance costs and also because there are often more efficient ways to achieve the same goals without using pattern matching.
