### ISSUE TITLE
Support for dotenv in SCC Docker/Kubernetes

### ISSUE THREAD

**Issue by jondubois** [SocketCluster/socketcluster#300]
.env files are a convenient way to load environment variables.
We need a way to load them easily when running SCC on local machine using baasil and also on Kubernetes (in this case the .env file will be inside a volume).

**Comment by jondubois** [comment]
Maybe some sort of optionsController which allows you to customize/transform the options object and runs BEFORE the SocketCluster object is instantiated. Right now there is a masterController but it runs AFTER the SocketCluster object has been instantiated. See https://github.com/SocketCluster/socketcluster/blob/master/sample/server.js#L55

**Comment by heiba** [comment]
This is desperately needed especially to enable https in a sane way.

So far to use Socketcluster boot options, I followed your advice and am usingbaasil run -e baasil run -e SOCKETCLUSTER_OPTIONS=

Currently to enable https, I had to do put the entire ssl key and cert in the baasil run command. Which is crazy! It was the only way to get it working, because putting fs.readFileSync like  isn't json compatible

baasil run -e SOCKETCLUSTER_OPTIONS='{\"appName\":\"exampl-loc-scc\",\"protocol\":\"https\",\"protocolOptions\":{\"key\":\"-----BEGIN RSA PRIVATE KEY-----<entire_key_here>.-----END RSA PRIVATE KEY-----\\n\",\"cert\":\"-----BEGIN CERTIFICATE-----<entire_certificate_here>-----END CERTIFICATE-----\\n\",\"passphrase\":\"example\"},\"logLevel\":3}'

**Comment by jondubois** [comment]
Ok since socketcluster `v5.15.0` you can specify the path to an options controller module as an environment variable `SOCKETCLUSTER_OPTIONS_CONTROLLER=/path/to/file.js` (this is optional of course).

If specified, this module needs to be a .js file and must expose a single `run` function in the format:

`run(options, next)`

The `options` argument represents the options object as pre-populated by SC (based on standard SC environment variables). You can modify this options object or create a new options object based on it... But you must pass it to the `next` callback once you're done populating its properties... E.g. `next(options)`.

**Comment by heiba** [comment]
We love you!!

**Comment by heiba** [comment]
Tested. Works like a lovely charm!
