### ISSUE TITLE
Typescript Support

### ISSUE THREAD

**Issue by ZenPylon** [SocketCluster/socketcluster#324]
Hi there,

I'm considering starting a project using socketcluster, but I don't see any typescript support as of yet.  If I'm mistaken, could you please point me to the right location?  If there is indeed no typescript support, perhaps I could create a branch and start adding some type definitions? 

That would be my first real open-source contribution through github! :O

Cheers,
Andrew

**Comment by sheeldotme** [comment]
@ZenPylon did you start on this?

**Comment by akshaychand** [comment]
@ZenPylon Is this in the works?

**Comment by ZenPylon** [comment]
Hi @akshaychand and @sheeldotme, sorry for the huge delay in response.  I had started, but abandoned it after not too long.  I decided to use Firebase as the websocket server.  Sorry - I think I deleted the small bit of progress I'd made :( .

**Comment by jondubois** [comment]
@akshaychand Since SC v9, there is already automatic TypeScript support. Just run the master (server.ts) with the `ts-node` command https://www.npmjs.com/package/ts-node - Also make sure that all your controller files (for child processes) have a `.ts` extension instead of `.js`. So for example it should be `worker.ts` instead of `worker.js`. You will need to also update the path to these controllers to account for this change (e.g. change these lines to have a `.ts` file extension instead: https://github.com/SocketCluster/socketcluster/blob/25b3f84f2bb69f92f9f9c404167c23ea27e5e919/sample/server.js#L20-L21).

**Comment by akshaychand** [comment]
Thanks @jondubois! Worked like a charm.
