### ISSUE TITLE
Retry Mechanism like MQTT for message queuing

### ISSUE THREAD

**Issue by astutesoftware** [SocketCluster/socketcluster#345]
Like with MQTT is there a way to ensure that an intended message is delivered to the client whenever the client gets disconnected and re-establishes the socket connection.

With mobile devices depending on the network they continuous go online and offline and will messages when there was no network.

How can one ensure that the messages intended are queued up and delivered later when the client becomes available?

**Comment by jondubois** [comment]
@astutesoftware SC is not a message queue; it's more lightweight.
There are many ways to make sure that clients receive a message after recovering from a lost connection.
You can store all messages in a log in the database (e.g. you could do it with MIDDLEWARE_PUBLISH_IN middleware) and when the client reconnects, they can fetch the latest log (snapshot) - That way they will get any missed messages.

If the sender goes offline, you can make the frontend wait for the connection to come back and then retry sending the message... You could store the unsent message in localStorage in case the user closes the browser before the message is sent while offline.

You can setup special channels unique to each user or category to check for read-acknowlegements. SC can support an infinite number of channels and they're cheap so you can create as many as you like.

**Comment by happilymarrieddad** [comment]
@astutesoftware I store every message in a long term log database and then I store the last 7 days in another database that gets cleared every night (any message older than 7 days) to ensure quick queries on recent changes. Then if I really need to go back I can but it doesn't cause major slowdowns on recent queries because 10's of millions of rows is slow to query on lol. This works pretty well for us. Not sure if it helps but it might work for you.

**Comment by astutesoftware** [comment]
Yes. @jondubois @happilymarrieddad - Thank you for your input.
Storing unsent message in localStorage is the way to go then. 

I keep hearing this "Channels are cheap". On a group chat room - Is it advisable to subscribe to a channel and intercept via middleware OR create an individual channel for each participant and emit messages to all of them who are supposedly in a room (No subscription - Just intent that they are currently in a room) ?

**Comment by jondubois** [comment]
@astutesoftware It depends on what your workload looks like. The advantage of using topic channels instead of private user channels is that you only have to check the user permissions once (e.g. inside MIDDLEWARE_SUBSCRIBE) and after that you can just keep publishing data to the target channel without having to do database lookups to see which users belongs to which groups/rooms.

Either way is fine though and allowing each user to have their own private channel is pretty useful for a lot of scenarios. The best solution for you probably comes down to efficiency and/or code complexity.
