### ISSUE TITLE
Automatic Docker builds of scc-broker and scc-state

### ISSUE THREAD

**Issue by toredash** [SocketCluster/socketcluster#348]
Could we add automated Docker builds of scc-broker and scc-state to Docker Hub ?

**Comment by toredash** [comment]
Is there anything I can do to help with this? Would be nice to get new images when new node security images are available.

**Comment by toredash** [comment]
@jondubois ping on this. Is there anything I can contribute with to get this in place ?

**Comment by jondubois** [comment]
Part of me likes it as a manual process because you can never be sure if upgrading to a new Node.js version could break things so it's difficult to automate. I feel like I'd have to setup a full CI pipeline first. This would create a lot of dependencies. In any case, I'd want to avoid spamming DockerHub with thousands of images like some other projects do. Maybe there is a sensible way to automate this? What do you have in mind?

**Comment by toredash** [comment]
Most important for me is that versions posted on npmjs and docker hub are equal. For instance, you have a docker build of scc-state:v1.5.1 (https://hub.docker.com/layers/socketcluster/scc-state/v1.5.1/images/sha256-eec28beea4c5f49de35009d53d651a51e3829614ca3c7786a88bad9b224ff33e), but this build is not present on npmjs (https://www.npmjs.com/package/scc-state)

You could use the specific hash for node, e.g. node: f6881d570a454691087553329e344f7f1eb4f80780507a2f69ebb46fe6a051f6 which really is todays :lts => https://hub.docker.com/layers/node/library/node/lts/images/sha256-f6881d570a454691087553329e344f7f1eb4f80780507a2f69ebb46fe6a051f6

Then you also could ensure that state/broker/socketcluster is running on the same node version, as you could end up with builds that is slightly different since they were built on different dates. All would be "node:lts".

**Comment by toredash** [comment]
Closing the issue since it isnt a prioritized tasks for now
