### ISSUE TITLE
Channels

### ISSUE THREAD

**Issue by carlosfusion** [SocketCluster/socketcluster#362]
Hello, how can i create reserved channel names in the server and dont allow users to create channels, only suscribe to created channels by the server.

**Comment by chnauman** [comment]
Hello @carlosfusion 
I am also new to socketCluster, reading the documentations at this time and saw your question. According to what I read till now.. I think the solution to your problem is:

You can add a middleware using scServer.MIDDLEWARE_SUBSCRIBE
in middleware function write an if to check the name by socket.channel == YOUR_RESERVED_NAME
on success use next(); other wise throw and error... 
you can read more details about the middle [here](https://socketcluster.io/#!/docs/middleware-and-authorization)

**Comment by amin-mir** [comment]
@carlosfusion You don't usually create channels. Sc brokers does this for you. They create and keep track of existing channels along with sharding and whole bunch of other stuff. Creating channels in server and subscribing users to them will defeat the purpose of pub/sub architecture. But as @chnauman said, you can use middlewares to prevent clients from subscribing to unwanted channels.

**Comment by chnauman** [comment]
Thanks @amin-mir 
I have another question, please give me your thoughts on that...
I am using an apache server to serve html pages with is running on server X.. I am using socketCluster only for pub/sub feature on server Y.. is there a way that I can some how authenticate user on server Y before they get connected to websocket, and remember I cannot ask user to login again so that I can verify credentials database, and I cannot save his user/pass in JS to send later for websockets connection, for security reasons...

**Comment by amin-mir** [comment]
@chnauman I am not sure if I have understood your question correctly, so let me know if my answer does not help. Are you using a microservices style (X and Y communicate) or client simply connects to both server X and Y? In any case, I would generate a JWT token after user logs in, on server X, and send it back to the user. Then when user tries to connect to server Y, he/she would send that token as well. The token basically contains everything you need about the user and you can also verify it with your private key to make sure it has not been tampered with.

**Comment by chnauman** [comment]
yes, @amin-mir .. you got it right... 
I thought that I can only verify JWT token on the server where I generated it... According to you I can create it on one server and check it on other to verify client... I should definitely read JWT documentation, before I go in detail tell me on thing... if I create JWT token on one server and then send it to other server to connect websocket.. how will second server verify that its right... second server does not already have that token, so it will be compared to what??

**Comment by amin-mir** [comment]
@chnauman To generate the token you need a private key. If both servers have the same key, then they can decode and verify the token. You don't need to store the token anywhere, and compare tokens against a dataset of generated tokens.

**Comment by chnauman** [comment]
@amin-mir, I understand..  Thank you so much for making it easier for me..
