### ISSUE TITLE
Delay in boradcast message when there is more clients connected!

### ISSUE THREAD

**Issue by hardikamutech** [SocketCluster/socketcluster#379]
Hello there,

We are developing one applications where we need to connect many clients with quick broadcast messages. we have tested your SocketCluster Server-Client stress test and also SCC app. we tested those apps in AWS instance t2.2xlarge which have 8 Cores and 32Gb memory.

Earlier we were only able to connect 25000-27000 concurrent client connection with a json array message as a broadcast message, But later with some server and code configuration we are now able to connect 64000 concurrent client in one channel using SCC and stress test app with same json array message as a broadcast. This is great and fine for now.

But issue is the broadcast message shows delay, means it received at each client end, you can say 7-8 seconds at 60000 client, and under 32000 its 4-5 seconds. we are using publish/emit method both gives same result.

please let us know if you have any idea to reduce this delay. *Our aim to broadcast message to all online(50k) clients per second without delay.*

Any help would lead in appreciation.

Thanks,

**Comment by toredash** [comment]
I've found that for best performance, use c4 instances and set aside one CPU core per 10.000 users. I've never consider T2 instances for this workload. 

With that, I'm able to push one message per second at around 1K.

I assume you are using at least 6_
-7 brokers in your setup?

**Comment by MegaGM** [comment]
Do you run ALL the stuff* on the same T2.Xlarge VPS?
If yes, then to get better results you, obviously, have to try to setup a real cluster, so add at least two VPS more, one for scc-broker, another one for your app (and a tiny VPS for scc-state ;) You'll get a big performance boost, probably. If you won't happy with the result, and you have free time, then read a couple of important notices:
1. SocketCluster works well with unbelievable amount of channels, channels are cheap, but it has some limitations when it comes to high throughput of a single channel. Why? Mostly because of brokers' architecture.
1. Brokers do shard channels among themself. So if you have 4 broker processes and only one channel to publish in tons of messages, then the only one broker, which is responsible for that particular channel, will work. The other brokers will be idle. If you wonder how SocketCluster determines which broker is responsible for a given channel name, you can check an example of the hashing algorithm at [sc-hasher repository](https://github.com/SocketCluster/sc-hasher/blob/master/index.js).
1. Once you get tired of looking at hashing functions, you can split your BIG_CHANNEL (f.e: `chat:room1377`) to, let's say 2 middle_channels, `chat:room1377/1` and `chat:room1377/2` respectively. So now 2 of 4 brokers will work at the same time on the same VPS. However, it'll require you to change some parts of your app as well. I won't describe possible server-side changes here, but on the client-side you usually can just setup the same watcher for both channels.
1. Still want more performance? You could try to add intentional delay between publishing/emitting underlying operations. You could setup something like classic `setTimeout(func, rand(1-500ms))` in the `MIDDLEWARE_PUBLISH_OUT` for the purpose. Yes, in theory clients will get message `rand(1-500ms)` later. However, in real world, the messages may be delivered **even faster** than if you'd publish them without the intentional delay. And, at the same time, you avoid at least some of cpu spikes of your app. It's like black magic, just try to play with the delay.
1. Still want better results of the tests? Notice that for stress testing you must have at least x3 more powerfull client-side VPS than server-side VPS. So to test one socketcluster app on 1x8CPU VPS, you need to run *at least* 3x8CPU VPS with socketcluster-clients.
1. Still want MOAR? You can use even custom codec engines for SocketCluster :D
1. Last but not least, try to improve your app's codebase. JSON array you said? I'd consider it as a bad practice to publish as a payload something else beside Javascript objects. <- Strongly IMO.


Just in case: don't forget to constantly look at cpu/io/etc of the stuff*, maybe you need more brokers, or scc-broker's, and less workers, or vice-versa. It's up to you to find the best balance for your app.

the stuff\* - scc-state, scc-broker, your sc-app with many workers and brokers, etc

p.s. I'm looking forward to some improvements in your app, let us know if it'd get better \*_\*
p.s.s. Since the issue is not an issue of the SocketCluster itself, rather a question, don't you mind closing it and join us in [SocketCluster Gitter chat room](https://gitter.im/SocketCluster/socketcluster) to continue the conversation?

**Comment by hardikamutech** [comment]
Hello to @toredash  and @MegaGM ,

Thanks a lot for your quick response as you guys suggested we have added 8 brokers with the same configuration, and we saw a major boost in performance. we are now getting message within a second to all connected client YaaY!! we have tested this with around 50k online client. On each client connection we are sending welcome message to that single connected client using emit method, and after all connection we are broadcasting message each second for stress test. Everything works perfect. Thanks again.

@MegaGM I also wanted to test your suggestion to send message on "setTimeout(func, rand(1-500ms))" in the MIDDLEWARE_PUBLISH_OUT, can you please explain how can I achieve this? 
we are using "scServer.exchange.publish('match',json_object);" where `match` is channel name and `json_object` is a big json data object.

A sample would be great.

**Comment by MegaGM** [comment]
@hardikamutech In the `MIDDLEWARE_PUBLISH_OUT` as well as in any other SocketCluster middleware, you have to call `next()` eventually. I was talking, essentially, about delaying the `next()` call. 

Here it is, a **dead simple example** ![](http://smayly.ru/gallery/ava/Kanade/13.jpg)
```js
function rand(from, to) {
  return 123
}

scServer.addMiddleware(scServer.MIDDLEWARE_PUBLISH_OUT, function(req, next) {
  setTimeout(function() {
    next()
  }, rand(1, 500))
})
```

Then you call your `scServer.exchange.publish()` as usual. The middleware will do its job.

**Comment by hardikamutech** [comment]
@MegaGM and @toredash Thanks for the responsive support! I really appreciate your contributions here. 
@jondubois Thanks for this scalable application. Keep up the good work guys.
closing this issue.

**Comment by MegaGM** [comment]
@hardikamutech I've found https://github.com/happilymarrieddad/sc-publish-out-queue/blob/master/index.js it allows you to specify "how many of messages will be published at a time". Maybe you'll find it useful.

**Comment by happilymarrieddad** [comment]
+1 on the sc-publish-out-queue =)
