### ISSUE TITLE
Workers spread horizontally but one main process?

### ISSUE THREAD

**Issue by Tuccinator** [SocketCluster/socketcluster#383]
I've been testing around with Socket Cluster and I'm enjoying it a lot. The one use-case I have for it would be to have workers spread out over multiple servers but all connected to a main master. So essentially the master will run some operations and publish to a Redis server. Each of the workers will be subscribed to this Redis channel and receive the data through that. Is there a specific way I should implement this or what?

**Comment by MegaGM** [comment]
I would advise you to try to avoid including business logic in the master process, where you call `new SockeCluster({...})` The better place for your code is workerController. If a worker crashes, the master will respawn it automagically. And it's easier to scale horizontally.

If you MUST use Redis, then try to look at https://github.com/SocketCluster/sc-redis
Basically, it publishes to Redis everything you try to publish from worker. When you `socket.exchange.publish('channelName', payload)`, the broker, which is responsible for that particular channel, will publish the `payload` to the Redis channel with the `channelName`. So you can setup a listener for the channel even from a completely another app.
With the sc-redis all pubsub channels will be synchronized across all brokers which are connected to the same Redis-cluster. Or even single Redis instance(not recommended for scaling horizontally).


However, that is not the best way to distribute data between hosts. You could simply setup SocketCluster cluster, which contains scc-state and scc-broker and your SocketCluster-based application, which connects to the scc-state via `SCC_STATE_SERVER_HOST` env variable. This is the recommended way. You can follow the guide https://github.com/SocketCluster/socketcluster/blob/master/scc-guide.md

Once you have a cluster, you'll be able to connect to it any SocketCluster-based application. So, in your case, you could put your code(which you wanted to put in a master process) inside the worker of **another** SocketCluster-based application, just create new. Then connect the new application to the same `SCC_STATE_SERVER_HOST`. That's it! Both SocketCluster-based applications now share all pubsub channels.
Btw instead of creating new project, you can create a new workerController.js inside your existing project and switch the workerControllers on some condition like env variable.

**Comment by Tuccinator** [comment]
The main process must only be run on one instance so in my case it wouldn't need to scale horizontally, but it's workers which connect to it will need to. Essentially there is a primary process on it's own server that all the workers will publish their data to. Do you think it would be fine to separate the entire logic of the primary process away from the socket cluster, into its own process, and only access the said primary process through Redis?

**Comment by MegaGM** [comment]
Yes, it definitely should be fine.
If you wanna leave you socketcluster-app w/o Redis, and connect to Redis on primary server only - simply `require('socketcluster-client')` inside all of your workers and connect them to the primary server.
You won't even need a cluster to do that. And you don't have to make a fullscale socketcluster application for the primary server. Just a single worker [socketcluster-server](https://github.com/SocketCluster/socketcluster-server) setup will be enough.

**Comment by Tuccinator** [comment]
All right. Thanks for the help!
