### ISSUE TITLE
Hold HTTP requests until a worker can handle them

### ISSUE THREAD

**Issue by wmertens** [SocketCluster/socketcluster#384]
When I send SIGUSR2 to the server, and then try to connect on HTTP, it will immediately fail until a worker started.

Can the behavior be changed so that when there are no workers available, the request is held for a bit? It takes 7 seconds for a worker to start, short enough to just hold the request but too long to go unnoticed.

**Comment by Hirbod** [comment]
That is actually something really important I've been struggling with, too. I've ended up using a timeout on clientside when receiving an error. Works OK for me

**Comment by happilymarrieddad** [comment]
@wmertens @Hirbod yea I have a delay in my client socket class wrapper as well.. good times...

**Comment by jondubois** [comment]
You may be able to achieve this by adding a proxy in front of your SC instance to achieve this.

**Comment by wmertens** [comment]
I already use nginx as a proxy, it doesn't do that either. It seemed to me
that sc is in a good position to do this; or is that hard due to its
architecture?

Could you point me to a starting point in the code where something like
this could be implemented?

**Comment by wmertens** [comment]
On Sat, Jul 28, 2018, 8:27 AM Aza Noriega <notifications@github.com> wrote:

> It seemed to me that sc is in a good position to do this
>
> Well, from my POV, if you get 50x errors from an upstream(SocketCluster),
> it seems impossible to do something about it on the upstream side, since
> it's probably is not running (yet or already). But you could intercept such
> errors in Nginx.
>

actually, the upstream is SC, which controls its workers, and is fully
aware that the workers are being restarted.

So handling it in nginx is too late, you lose information.

Could you point me to a starting point in the code where something like
> this could be implemented?
>
> @wmertens <https://github.com/wmertens> Look at the following Nginx
> directives:
> proxy_intercept_errors
> <https://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_intercept_errors>
> error_page
> <https://nginx.org/en/docs/http/ngx_http_core_module.html#error_page>
>
I know that nginx can do it, provided you run an extra process that
pretends to be an upstream. It will hide real 500 errors, and it is
cumbersome to set up. In SC it's probably only a few lines of code that
will benefit a lot of users.

**Comment by MegaGM** [comment]
@wmertens Lemme try to answer once again. From scratch.

> Can the behavior be changed

Yes.

> so that when there are no workers available, the request is held for a bit?

No. SocketCluster doesn't manage http requests in the way you apparently think it does. SC has no built-in load balancer(since `socketcluster@2.0.0`, iirc). Load balancing now is done by OS by default, or via `cluster` module if you choose `cluster.SCHED_RR` as the cluster `schedulingPolicy`.
So currently SC cannot "hold" a request while workers are being restarted. Neither it can accept any http requests.
Because SC master processes(in this context I mean `scworkercluster.js` + your `server.js`) don't listen for client connections at all.
The http servers are being instanciated, and the requests are being processed **within the worker controllers**(`SCWorker` + your `worker.js`), which are being restarted atm.
The master processes don't know and even **should not** know anything about the requests, otherwise vertical scaling would be extremely inefficient. So it goes.

> Could you point me to a starting point in the code where something like this could be implemented?
> proxy_intercept_errors  
> error_page  

The `run()` method in the `worker.js`. If you're using `express`, you could setup an error handler for the `app.use()`, although I doubt you need that.

> It takes 7 seconds for a worker to start, short enough to just hold the request but too long to go unnoticed.

If you want something like "zero downtime deployment", you could just kill a worker per the 7 seconds... ...just kidding :stuck_out_tongue_winking_eye: let's do it ASAP.

There is at least two ways of achieving something like ZDD.

#### Easy way:

In the example below, we won't kill all workers immediatelly(default behavior), but will respawn them one by one in a chain, like if we'd use `async.eachSeries()`.

Cons:
If you have 6 workers, it will take 7 * 6 = 42 seconds to complete. It's not a big deal on its own, because for these 42 seconds you still will have running other 5 workers. However, you'll have to always keep in mind, that for those 42 seconds some of workers will be updated already and some not yet. This might be a source for unexpected issues. So if you've changed 50% of `worker.js`, it could be more safely to kill all workers at the same moment, as `socketCluster.killWorkers()` does.

Clients will be disconnected-reconnected twice within the 42 seconds. You can decrease reconnection delay for clients(`options.autoReconnectOptions`), because there always will be some workers alive to connect to.

Pros:
Less downtime, less non-200 responses. If you have a little cluster with just 2 socketcluster-nodes(aside from nodes with `scc-state` and `scc-broker`), you won't have such a big CPU/RAM/SSD/TCP spike because of outage of 50% of cluster. Because most of client will stay on the node which we're doing magic on. So the lag spike will be `amount of workers` times less.

As a bonus, if you messed up with app code, and your updated `worker.js` throws something, only one of all workers will be affected after sending SIGUSR2. The rest workers won't be restarted, because the first one is unable to start properly.

**`server.js:`**

```javascript
const options = {
  rebootOnSignal: false, // disable internal SIGUSR2 handler
  rebootWorkerOnCrash: true,
  // other options
  workers: 7,
  brokers: 1,
  // ...
}

const socketCluster = new SocketCluster(options)

// and setup our own instead
process.on('SIGUSR2', () => {
  let i = 0

  const killWorker = workerId => {
    socketCluster.sendToWorker(workerId, { foo: 'bar' })
  }

  const killNext = () => {
    if (i < options.workers) {
      killWorker(i++)
      socketCluster.once('workerStart', killNext)
    } else
      i = 0
  }

  // kill worker with worker.id === 0
  killWorker(i++)
  // once worker 0 has been respawned, kill worker 1, etc
  socketCluster.once('workerStart', killNext)
})
```

**`worker.js:`**, within the `run()` method:

```javascript
class Worker extends SCWorker {
  run() {

    this.on('masterMessage', payload => {
      if (payload.foo !== 'bar')
        return

      this.close(() => {
        process.exit(0)
      })

      setTimeout(() => {
        process.exit(1)
      }, 10000)
    })

  }
}
```


Now the most important. The example hasn't been tested. I run it locally, everything looks fine to me, but I didn't make any "serious" tests. So I do not recommend you to use the example on production :slightly_smiling_face:

#### Hard way:
Fork workerCluster controller.

`cluster` shares socket handles among master and childs.
(Re)spawn any piece of code which will have the handle.

Rewrite lifecycle of workers(not so much).
Directly communicate with other workers, and main SC master.
Listen for client connections on the same port which all workers do listen to.

*Cons*: the major one - you'll have to implement your own `cluster.schedulingPolicy`
*Pros*: unlimited possibilities.


P.S. I still have a feeling like I got you wrong. Could you explain in more detail what exactly do you want to achieve?

**Comment by wmertens** [comment]
@MegaGM Aha! Thanks for the detailed answer!

No, I think you got me right :) I was mistakenly thinking that SC proxies the connections to the workers, and now I realize that would be very inefficient.

How about this approach, the halfway between your approach 1 and 2:

* Kill+replace all workers (gracefully) with a new `SCWorker` that just holds incoming requests until signaled
* Once all workers are replaced, send a signal
* The signal causes each SCWorker to `require()` the new `worker.js` and pass the held connections to it

Would that work?
