### ISSUE TITLE
Multiple questions regarding implementation with Redis

### ISSUE THREAD

**Issue by Tuccinator** [SocketCluster/socketcluster#387]
I have a few questions that I would love to get addressed.

**1.** I have a backend that is not connected with socketcluster, but with Redis. Essentially when someone sends a request through SocketCluster, it will do some work in the backend, and later publish the result to Redis, where the workers are subscribed to the event. It will then send the information to a specified channel based on the data received in the backend.

Each worker is subscribed to the same event so when it receives the publication, will it relay the information multiple times to each socket? Say there are 4 workers, will it publish to the same channel 4 times?

Is this bad for scalability?

**2.** I am currently storing the user connections and the online count within Redis. Upon the first connection by a unique user, it will create a key within Redis to hold the number of connections by that user. So if the user connects yet again through a different tab or browser, it will add 1 to the number of connections by that user. So effectively this keeps the online count unique because it only increases when there is a new unique connection.

My problem is that when the worker crashes or I restart the cluster, the data still persists. So each person who reconnects, it will double their connections, even though it should stay the same. This also creates a problem with the online count because now when they close the 2 tabs (connections), it will now be down to 2 connections and thus the online count won't decrease.

**Comment by MegaGM** [comment]
**1st question: it's up to you.**
> @Tuccinator wrote: Each worker is subscribed to the same event so when it receives the publication, will it relay the information multiple times to each socket? Say there are 4 workers, will it publish to the same channel 4 times?

If you subscribe to the redis channel via a redis client inside each worker, then each worker will get the message from your non SocketCluster-backend. Then, if you'll `scServer.exchange.publish()` within listiners for the redis channel *inside each of your 4 workers*, the frontend clients will get the message 4 times. Although, if you'll loop through clients' sockets manually and call `.emit()`, the clients will get the message one time only. But, please, don't do that unless you're absolutely positive you must to.

To seamlessly integrate SocketCluster with Redis, you could use https://github.com/SocketCluster/sc-redis.

The execution flow could look like:
- a client `.emit()` a command for a worker to start a job
- the worker sends the command somehow(as you said via redis) to your non sc-backend, let's say `pubClient.publish('myChannelForNonSCBackend', data)`
- the non sc-backend finishes the job and publishes the result in the desired channel (the one, to which the frontend clients are subscribed to) `publish channelDesiderByClients 'o:{"a":123, "b":456}'`
- The message will then be delivered to each frontend client, which is subscribed to the channel, automagically across all workers. And, of course, the message will be sent once

Notice that, in order to get picked by `sc-redis`, the message should be in a specific format. You can see some examples in ReadMe and in the source code https://github.com/SocketCluster/sc-redis/blob/master/index.js#L38-L43.

Or it could also look like:
- a client `.emit()` a command for a worker to start a job
- the worker sends the command somehow to your non sc-backend, including `requestedBy: worker.id`
- the non sc-backend finishes the job and publishes the result to a channel all workers are subscribed to. Don't forget to include the same `worker.id` as the `requestedBy`
- the workers are checking if their `id` is equal to the `requestedBy`. If yes, then do some additional computations, then `scServer.exchange.publish()` to the channel desired by frontend clients
- The message will then be delivered to each frontend client, which is subscribed to the channel, once only

Consider, please, there might be better ways to resolve your issues, which I just don't know/don't remember.


**2nd question:**
A turnkey solution for the purpose is made already. https://github.com/SocketCluster/sc-stateless-presence

It enables you not only to know on both(server and client) sides, how many users are online overall, but how many users are online and subscribed to a specific channels, and more.

Simpliest way to count overall online is to subscribe **all** the clients to a channel, with no intent to publish to the channel, just to track the clients online status.

And since `sc-stateless-presence` is... stateless :) It means if a worker will crush, all the users of the worker will be marked as offline inside other workers as soon as `presenceTimeout` ms will expire.

**Comment by Tuccinator** [comment]
Thanks for your answer regarding both of the questions.

sc-stateless-presence says "It's ideal for tracking the presence of users within channels that have fewer than 100 concurrent subscribers online at any given time." The channel will have up to 5000 concurrent connections so it sounds like this approach wouldn't scale very well. If someone has 3 tabs open, does it count all 3 tabs as separate subscriptions?

**Comment by MegaGM** [comment]
If the client, which has opened 3 tabs, is authenticated and has `username` inside its `authToken`, then all 3 tabs will be counted as one user.

However, on the server side you still can get individual sockets for the given username if you really have to, because all 3 tabs' sockets will be stored under the same username, you could see it at the line https://github.com/SocketCluster/sc-stateless-presence/blob/master/index.js#L88
`presence.workerSubscribers[channelName][username][socket.id] = socket`

> within channels that have fewer than 100 concurrent subscribers

100 - it is not a quite accurate number of subscribers `sc-stateless-presence` could work well with. TBH I'm not sure if it will be okay for 5k subscribers, but I'd definitely try. Probably you'd like to decrement `presenceInterval`. Because, by default, the plugin will publish an array of usernames, *per each channel you're tracking for*, once per 10 000 ms.

If you track presence in one channel only, which has 5k authenticated subscribers, then it means **each frontend socket will get an array of 5k strings (usernames of clients who are in the channel now) each 10 seconds**.

It's quite okay to have an array with 5k strings inside each of your workers' memory, but it might not be okay to send so much data so often. (the array with 5k strings \* 5k sockets), it's 25 000 000 usernames to send over the wires each 10 seconds. Just imagine a common username, let's say it has approximate length of 7 bytes. 25kk \* 7 is more that 150MB/10s. That's not quite accurate as well, so irl you'd have to use at least +30MB/s more bandwidth to be able to use the `sc-stateless-presence`.

To reduce the load, you could set `presenceInterval` to let's say 60 000 ms. However, if a worker will crush, the other workers will identify the clients of the worker as offline after the `presenceTimeout` which is by default `presenceInterval * 1.3`. So such users will be marked as offline within 78 seconds time span.

**Comment by MegaGM** [comment]
I'm just going to leave this here
https://github.com/SocketCluster/sc-stateless-presence/issues/2
https://github.com/SocketCluster/socketcluster/issues/334

You could combine `sc-stateless-presence` with https://github.com/happilymarrieddad/sc-publish-out-queue and with this feature https://github.com/SocketCluster/socketcluster/issues/334#issuecomment-349571106, to get better performance.

**Comment by Tuccinator** [comment]
Well I don't need the actual usernames, just the online count.

Referring to ``334``, do you know how many subscribers we are talking about? I'm looking to publish a message every 200 milliseconds to all subscribers. The max amount of subscribers would be around 5000. Unlike what "toredash" said, I cannot implement a 1-5 second delay.

**Comment by MegaGM** [comment]
> Well I don't need the actual usernames, just the online count.


Notice, that if you won't use usernames at all, you won't be able even to tell how much sockets are belong to authenticaded users, how much are unauthenticated, how much are actually clients which just have opened multiple tabs. So it's better to track them after all. Otherwise you could simply access `scServer.clientsCount`, to know how much users are currently connected to the particular worker.

> every 200 milliseconds to 5k subs

I'd advise you to split your BIG_CHANNEL into many little_channels. I'm just speculating, but if you'd split your **1x5k** to **5x1k** channels or even **10x500**, you definitely will see a noticeable improvement in performance.
I'd suggest you to read some related stuff:
[a message](https://gitter.im/SocketCluster/socketcluster?at=5aa67ae2a60157d62fd9c650) and [an issue](https://github.com/SocketCluster/socketcluster/issues/379)

---

Back to tracking online clients... Transmitting the big array of usernames each 10 secs - it's the bottleneck of the presence plugin anyway, so you could fork the `sc-stateless-presence`, or even make a PR :smile_cat:

Basically you just don't want to send 5k usernames to each socket each 10 seconds. Better send them once instead, when a socket is (re)connecting. So you'd still have pretty much correct data about online/subscribed/authenticated clients. And, at the same time, you'll cut probably 90%+ of `sc-stateless-presence`'s bandwidth usage.

Please, look at [the important piece of code](https://github.com/SocketCluster/sc-stateless-presence/blob/master/index.js#L40-L49).
Essentially you want to remove `setInterval()`, and execute almost the same code from setInterval's callback, inside a listener for either `socket.on('connection')` or `socket.on('your-custom-event')`. And you better use `socket.emit()` there, instead of `.publish()`, to send the info to a single socket only.
You would like to change `presenceTimeout` as well. And the way the client part of the plugin marks users as offline via a setInterval as well. And, apparently, something else. I could make the PR myself, but I'm not sure if it will be done soon enough.

```js
this.exchange.publish(presenceChannelName, {
  type: 'ping',
  timeout: this.presenceTimeout,
  users: users
});
```
`users: users` here is the array of 5k usernames.
