### ISSUE TITLE
SCC horizontal scaling. Target a specific user on another node.

### ISSUE THREAD

**Issue by ayberkanilatsiz** [SocketCluster/socketcluster#425]
Hi, Vertical scaling works fine with scc-state and scc-broker. 

Publish clients emitting are working awsome but i have problem. I want emit inbox to user which is connect other server.

<img width="961" alt="screen shot 2018-06-06 at 11 19 12" src="https://user-images.githubusercontent.com/7476653/41025795-8ab5f6c2-697b-11e8-8050-7af95b270779.png">

I want to emit inbox to **User B** from **Socket Cluster X**. I know **User B** socket id.

I did `scServer.clients[socketId].emit('inbox', inbox);`. It works on only single cluster but now 
i get `TypeError: Cannot read property 'emit' of undefined`

**Comment by MegaGM** [comment]
This is a placeholder for the answer, I'll edit this message sometime soon.

**Comment by MegaGM** [comment]
### Essentially you want to deliver a message:
1. **From any part of your application**  
  *server-side JS, client-side JS, client-side with client written in [any other language](https://github.com/SocketCluster/client-drivers), external apps like Redis, AMQP, MQTT, etc.*

2. **To a specific user** which might have multiple opened tabs, maybe uses a phone, a laptop and a PC at the same time. In other words, the user might be connected to multiple workers on the same node or on multiple nodes simultaneously.

If that's the case, you could let SocketCluster handle it for you. How?

* User `Bob` which is connected to node-1, subscribes to a channel, let's say `bob-private-channel`.
* User `Alice`, which is connected to node-2 via her phone, and to node-X via her laptop, subscribes to a channel `alice-private-channel`.


**That's it! Now you can publish a message to `Bob` or to `Alice` from anywhere, where you have `.publish()` method.**

```js
// in a worker on socketcluster-node-1
const payload = {text: 'Hello Alice!'}
scServer.exchange.publish('alice-private-channel', payload)
```
In this example the `payload` from a worker on node-1 will be automagically (via scc-broker-client and scc-broker) delivered to node-2 and node-X, and pointed to the exact same workers, which `Alice` is connected to. Hence her phone and laptop will get the payload accordingly, since they're both subscribed to the `alice-private-channel`. Just like that:
```js
socket.subscribe('alice-private-channel').watch(handleDirectMessage)

function handleDirectMessage(payload) {
  console.info(payload.text) // => Hello Alice!
}
```

![](https://i.imgur.com/h4bJTrM.png)

Well, deeply thinking, strictly speaking, the payload won't be **"delivered to workers"**. It'll be rather **published to a channel** and might be consumed by **subscribers**.


You definitely would like to read that article [an article SocketCluster Design Patterns for Chat](https://blog.baasil.io/socketcluster-design-patterns-for-chat-69e76a4b1966)
And, of course, the docs https://socketcluster.io/#!/docs
Feel free to ask any questions in the [Gitter chat room](https://gitter.im/SocketCluster/socketcluster)

**Comment by ayberkanilatsiz** [comment]
@MegaGM it works like a charm! Thankss =)

**Comment by happilymarrieddad** [comment]
You can assign each user to their own channel (i.e. subscribe(user.id.toString())) and then send emails/messages to that channel. That's essentially what we do for chat messages that are direct messages.

**Comment by ayberkanilatsiz** [comment]
I use it for direct message and it works. It's for inboxes it means place where you show the profiles that the member is already chatting.
