### ISSUE TITLE
Kubernetes "Server" Code

### ISSUE THREAD

**Issue by firrae** [SocketCluster/socketcluster#486]
Hi there,

I've been trying to figure this out for a bit now but I'm still not fully clear on how this all works. We've identified a number of use cases for our project and SocketCluster seems to check all the boxes where most don't. The thing I am stuck on is the following:

We have set up SocketCluster using the Kubernetes guide linked to on the front page of the website. This seems to be up and working as we get the "random" event coming through perfectly fine. In this method though I am confused as to where we write code that responds to socket requests from clients? Are we supposed to use the socketcluster-server NPM package to create our logical nodes? Though this doesn't seem correct though.

At this point, we seemingly have a working cluster, but I'm not sure how to tie our server code into it after reading about SocketCluster for a number of days. I don't know if that's on my inability to understand the documentation or a shortcoming of the documentation. If the later I hope I can help get clarification for myself and others that end up in our situation.

**Comment by firrae** [comment]
So the answer(s) that have come up are the following:

1. The SocketCluster Kubernetes Guide creates a default, example, SocketCluster server/worker that generates the random number and emits it over the "random" event.

2. To remove the "random" event, remove the worker or stop using the example server and make your own.

3. SocketCluster is actually 3 parts: 

   1) A state manager: this manages state as the socket connections spread across many nodes.
   2) A message broker: this seems to manage ensuring messages are sent only to the correct places.
   3) A server: this is where your application logic goes. This connects to both the broker and state manager so it can be scaled horizontally.

4. Yes, we did have a working cluster.

Does this seem like a fair breakdown @jondubois?

**Comment by jondubois** [comment]
1. Yes because the `socketcluster` image which is currently available on DockerHub is built from that sample. It's possible to attach a volume container to replace the default worker.js file. IMO, we should remove that sample logic from the socketcluster repo in the future because a lot of people just want to run the container as-is without adding any custom logic.

2. Right now yes, you an build your own image or you can attach a new worker.js file as a volume to the Docker container (but it's a bit tedious to do manually and requires a good understanding of Docker). There is a command line tool which makes this easier: https://www.npmjs.com/package/baasil

3. Yes everything you said here is essentially true. For horizontal scalability across multiple machines there is `scc-state`, `scc-broker` and `scc-worker` (aka `socketcluster` Docker image).

**Comment by firrae** [comment]
We do plan on building it ourselves. Our DevOps guy prefers to understand everything that is going on, and so do I to some degree, so he managed to get it all up and running straight through Rancher and kubectl. Obviously I'll use the example code where I can to speed up the bootstrap a bit, but this clears up a lot of my confusion.

I'll close this issue at this point. Hopefully if anyone has the same mental block of what is going on as I did they can find this and get to a level of clarity.

**Comment by happilymarrieddad** [comment]
@firrae If you need any help, we are using SCC in production right now in a Kubernetes cluster on AWS.

**Comment by firrae** [comment]
@happilymarrieddad I think I have what I need for now. I just need to think through the implementation and where it fits exactly in our stack. Socket.io wouldn't work in our case, but this should if implemented correctly.

**Comment by happilymarrieddad** [comment]
@firrae Good to go man. Yea, we actually went away from SCC and are just using dynamic instances of the workers because the clients don't need to communicate with each other anymore. It's a completely different way of handling it but I still have the "old" code, software... things that are months old become "old" lol... it might be useful if you need it... not sure. Good luck!

**Comment by poppahorse** [comment]
@happilymarrieddad are you doing this via Baasil and Rancher out of interest? or directly with Kubernetes? Not sure I want them as dependencies in the project, especially as on the face of it they are paid services, especially Baasil being a 30 day trial only. Most information / docs / articles I can find seem to heavily rely on Baasil, and information with vanilla Kubernetes seems light.

Also just noticed, I think I watched one of your videos recently while I was determining if SCC scalability was suitable - https://www.youtube.com/watch?v=A8YrQIsFNdA :)

**Comment by happilymarrieddad** [comment]
@poppahorse Yea, sorry I'm not using Baasil. I'm just using Kops and AWS. That being said, I use ingress-nginx for pointing to the internal SCC deployment via the ClusterIP Service. I then have the client apps connect to that endpoint and they are put on one of the broker servers. That broker server listens to changes in the database and sends those changes to the client. Essentially using the database as the sub/pub kind of and then using SC as the message system for publishing those events to the clients. The more clients there are the more brokers that are spun up by kubernetes and it just scales over time. The client's don't really talk with each other but at some point I probably will build out that feature.

As far as that video is concerned, I believe it is really old... I need to make new ones.
