### ISSUE TITLE
SCWorker options.authEngine being overridden by defaults

### ISSUE THREAD

**Issue by vgw-rhysc** [SocketCluster/socketcluster#514]
Should the `options` being passed in be overridden by the defaults, or have I missed something here?
Im trying to set the AuthEngine as per docs: https://socketcluster.io/#!/docs/api-scworker 

> You can also use the options object to pass a custom authEngine and codecEngine to the SCWorker instance.
However it seems that the param is just overwritten in this line here.
https://github.com/SocketCluster/socketcluster/blob/master/scworker.js#L82
```
var workerOptions = Object.assign({}, options, workerInitOptions);
```
Should this be :
```
var workerOptions = Object.assign({}, workerInitOptions, options);
```
❓

**Comment by MegaGM** [comment]
@vgw-rhysc Nice catch, thank you!

The option to pass custom `authEngine` in `SCWorker` constructor is there since [SocketCluster `v14.2.0`](https://github.com/SocketCluster/socketcluster/commit/5c0e57bfcbf0487e3600e4732b4599384ad0107b)


```js
var workerOptions = Object.assign({}, options, workerInitOptions);
```
AFAIK, the wrong order of the arguments hasn't caused any observable issues so far. But that's just a coincidence, because `workerInitOptions` object never includes nor `authEngine` nor `codecEngine` properties.

So, in fact, even with the wrong order of assigning properties, the `authEngine`, which is passed to the `SCWorker` constructor, is not being overridden anywhere.


The following example works fine (throws the expected exceptions) with SocketCluster `v14.4.1`
```js
const myMockAuthEngine = {
  itsMyMockEngine: true,
  verifyToken: () => {
    throw new Error('My custom verifyToken function has been invoked')
  },
  signToken: () => {
    throw new Error('My custom signToken function has been invoked as well')
  },
}

new Worker({
  authEngine: myMockAuthEngine,
})
```

I'll open a PR to swap the arguments positions.

@vgw-rhysc Could you, please, provide an example of code which fails to setup your custom `authEngine` correctly?

**Comment by vgw-rhysc** [comment]
Sorry this may have actually been me confusing the SC Server and SC worker - i had added logging into to both and have likely misread the logs.
I think we can close this. I guess i am a bit confused as to why we have an auth engine in the SC Server that is independent to the SC Worker however?

**Comment by MegaGM** [comment]
@vgw-rhysc said:
> an auth engine in the SC Server that is independent to the SC Worker


Workers don't use `authEngine` at all, only SC Server does.  
Each `SCWorker` spawns its own copy of `socketcluster-server` and simply [passes the `authEngine` option down to it](https://github.com/SocketCluster/socketcluster/blob/49a81d774cb621fa6483a8cb47d0a852d4e32fa6/scworker.js#L96).
