### ISSUE TITLE
Hello i had query

### ISSUE THREAD

**Issue by Dj-jom2x** [SocketCluster/socketcluster#521]
what are workers and brokers .. how much do I need if I had .. 10 cores CPU. I feel they act as a thread xD I don't know.. I want to utilize all the 10 cores and 60gb ram 

I finish writing the ngx-socketcluster-client for angular.. and that question above popup .. reading docs about it still confuses me. 

I wanted to switch to socket.io to socketcluster for my next proj.

that question above + how to create your own parser. like socket io had

**Comment by jondubois** [comment]
@Dj-jom2x The easiest solution is to just create 10 workers and 10 brokers (as many of each as you have CPU cores) but if you want to optimize things (to reduce context switching), you should make it so that `workers + brokers = CPU cores` so you need to figure out what ratio works for your scenario. 

The workers:brokers ratio is loosely correlated to the subscribers:publishers (I.e. consumers vs providers, readers vs writers) ratio of your system.

For example, a system like Reddit will have a high ratio of consumers compared to providers while a system like Whatsapp will have a more even ratio.

The fewer publishers you have, the fewer brokers you need.

**Comment by Dj-jom2x** [comment]
is SocketCluster faster than socket io? I think that 5 workers and 5 brokers is fine...

**Comment by Dj-jom2x** [comment]
good script <3 finally done xD I thought it will take an age for me to migrate haha.

ngx-scluster ✅
packed all data but keep the length same ✅ 

I cant packed all socket.io packets... only those I can manually emit are being packed else both cant read each other.... but here it works great ✅  all is packed.

![image](https://user-images.githubusercontent.com/12135498/69337614-44632080-0c9c-11ea-9547-bcadfdad1c05.png)

**Comment by happilymarrieddad** [comment]
@Dj-jom2x if you can try to use something like Kubernetes that will allow you to autoscale and then use the OS package to grab the number of CPU cores on the virtual instance. This will alleviate all the concerns with "how much to use". I hope this helps!
