### ISSUE TITLE
Can I listen any event just before any channel is garbage collected i.e. When we have Zero subscribers to a channel?

### ISSUE THREAD

**Issue by Shankar-khati** [SocketCluster/socketcluster#551]
My use case is simple when the conversation on an SC cluster gets completed I need to dump all data from the cache to persistent. But for that, I'm looking for an event or callback which could be executed just before the channel is garbage collected.

**Comment by Shankar-khati** [comment]
@jondubois, @MegaGM, @sacOO7 can anyone give me any suggestion for the above statement?

**Comment by jondubois** [comment]
@Shankar-khati Sorry for the delay in answer. Maybe you figured it out already.
You can use the `'unsubscribe'` event on the server socket (on a per-socket basis); it triggers when either:

- The user explicitly unsubscribes from a channel.
- The user disconnects or becomes disconnected.

See https://socketcluster.io/docs/api-ag-server-socket/

Alternatively, you can listen to the `'unsubscription'` event on the server (it aggregates all the 'unsubscribe' events from all sockets which are attached to that server/process) - It allows you to perform the unsubscription handling for all sockets and channels from a central place (instead of dealing with it one socket at a time).

**Comment by Shankar-khati** [comment]
@jondubois currently I'm listen on subscribe and unsubscribe event on server and maintain a counter for each channel at my end, just wanted to know if you guys have any event from scc-broker-client or scc-state where I can expect an event when a Channel submitted to garbage collector or when the first subscription happen to the channel.
