### ISSUE TITLE
badSocketAuthToken event not triggering

### ISSUE THREAD

**Issue by priyadars-hi** [SocketCluster/socketcluster#576]
Hello,

I am using v17 code. 'badSocketAuthToken' event of AGServer and 'badAuthToken' event of AGServerSocket not triggering after client connect with expired or old auth token.

I am testing a scenario where client redirects to login page when server restarts and client tries to connect again with old authtoken.  for that server should emit badSocketAuthToken event to check the scenario, but that's not triggering. 

If possible create 'badAuthToken' event on client socket as well in future builds.

**Comment by MegaGM** [comment]
Cannot reproduce.  
All the following examples correctly show `jwt expired`, `invalid token` and `invalid signature` messages.  
```js
!async function listenWarnings() {
  for await (const { warning } of agServer.listener('warning')) {
    console.warn('WARN: ', warning.message)
  }
}()
```
```js
!async function listenBadSocketAuthToken() {
  for await (const { socket, authError, signedAuthToken } of agServer.listener('badSocketAuthToken')) {
    console.error('badSocketAuthToken: ', authError.message, signedAuthToken)
  }
}()
```
```js
!async function listenConnections() {
  for await (let { socket } of agServer.listener('connection')) {
    !async function listenBadAuthToken() {
      for await (const { authError, signedAuthToken } of socket.listener('badAuthToken')) {
        console.error('badAuthToken: ', authError.message, signedAuthToken)
      }
    }()
  }
}()
```

I'd like to clarify that:  
`badAuthToken` in the example will be emitted only if you will use `socket.authenticate()` and won't be emitted on (re)loading of a browser tab. Because in that case authentication happens as a part of Handshake, before the listener is set.  
`badSocketAuthToken` will be emitted in any case.  

@priyadars-hi Please, try to use the provided `badSocketAuthToken` code example in your app. Feel free to reopen this issue if you won't succeed.

**Comment by priyadars-hi** [comment]
Thanks for the reply, your solution working fine!!
