### ISSUE TITLE
Potential security issue

### ISSUE THREAD

**Issue by psmoros** [SocketCluster/socketcluster#581]
Hello 👋

I run a security community that finds and fixes vulnerabilities in OSS. A researcher (@0xshdax) has found a potential issue, which I would be eager to share with you.

Could you add a `SECURITY.md` file with an e-mail address for me to send further details to? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) a security policy to ensure issues are responsibly disclosed, and it would help direct researchers in the future.

Looking forward to hearing from you 👍

(cc @huntr-helper)

**Comment by MegaGM** [comment]
Thank you for contacting us!
Personally I have no experience with `SECURITY.md` files yet, perhaps we'll add one later.
In the meantime you could contact the leader of SocketCluster team @jondubois via personal email [grosjona@yahoo.com.au](mailto:grosjona@yahoo.com.au)
or via direct messages in Gitter https://gitter.im/jondubois

**Comment by psmoros** [comment]
Ok thank you! :))

**Comment by jondubois** [comment]
@psmoros Thank you for your report.

The issue you mentioned only appears to affect docker commands which are intended to be executed in a dev (not production) environment on the user's own machine (which they have full control over). It doesn't appear to allow privilege escalation since the user already has full access to code/containers running on their own host machine and could execute any command they like inside (or outside) containers anyway. It's also important to note that the user in our case is either a developer or sys admin so they are trusted; I cannot see any realistic scenario whereby an unauthorized user would be able to execute the commands you mentioned without already having full access to the host.

That said, if you can give specific examples of how it could be a problem for some users in our particular case (e.g. maybe an unintended use case which we haven't considered), feel free to send me a follow-up email.

**Comment by psmoros** [comment]
Thanks @jondubois! @0xshdax will follow up if they have any disagreements for the moment we'll consider this report invalid... Sorry for wasting your time

**Comment by 0xshdax** [comment]
Hello @jondubois , 

This issue is like [CVE-2021-44684](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-44684), If the developer does not accept this issue, there is no problem. I am simply informing them of potential security issues.

Thanks.
