### ISSUE TITLE
HTTP/2 server support?

### ISSUE THREAD

**Issue by IngwiePhoenix** [SocketCluster/socketcluster#68]
I just wondered if there is a way that a SocketCluster server would be able to use a HTTP/2 server. I saw one on NPM that supports the actual http API.

https://www.npmjs.com/package/http2

**Comment by jondubois** [comment]
@IngwiePhoenix Yes, good idea. I will look into it this weekend.

**Comment by jondubois** [comment]
@IngwiePhoenix I would prefer to wait a bit longer before allowing HTTP2 support in SC.
I spent some time reading discussions in Node.js issues section and it seems that it's still undecided how and when HTTP2 will be integrated into core.

I think we could in theory add support for HTTP2 before it becomes part of Node.js core, but looking through the issues list: https://github.com/molnarg/node-http2/issues - It seems like the http2 module is still in its early stages. I will keep an eye on the project and when it looks like it's stable enough for production use, we can allow people to use it instead of the regular http1.1 - Probably by setting the prototocol option of SC to 'http2'.

We can leave this issue open as a reminder to check up on it from time to time.

**Comment by jondubois** [comment]
At first glance, it looks like it may be possible to make a small change to SC to allow providing a custom server object (this could be a HTTP2 server or SPDY server or whatever).

I will look into this sometime next week hopefully.

**Comment by jondubois** [comment]
When instantiating the main SocketCluster instance (in server.js), you can now pass an optional 'httpServerModule' - It should be a string (module name/path). So if you want to use the http2 module, you can set it to 'http2'.

Note that http2 doesn't appear to work with express yet though, so if your SC worker uses express then it will throw a weird error. See https://github.com/molnarg/node-http2/issues/100

**Comment by ayZagen** [comment]
@jondubois http2 is stable now. I tried `httpServerModule` option but it seems not working.
