### ISSUE TITLE
Process Monitoring

### ISSUE THREAD

**Issue by mastayoda** [SocketCluster/socketcluster#69]
Greetings,

I'm a graduate student researching on high-performance computing and SocketCluster is our first option to implement an experimental system for distributed processing. In order to provide evidence about the efficiency and resource usage of the system, we need a way to collect metrics about CPU, Memory etc. I'm currently using PM2 as a subprocess manager and works nicely since I can use it programmatically. I'm aware that SocketCluster has its own process manager, is not there a way I can integrate PM2 or another way to monitor those sub-processes (workers, balancers)?

Thanks in advance, I really appreciate it.

**Comment by jondubois** [comment]
@mastayoda That sounds interesting.
Yes, right now SC has its own process manager - It's all integrated since there needs to be coordination when launching and re-spawning various processes.

You can monitor using various OS commands. Here are some of the most popular ones for Linux: http://www.tecmint.com/command-line-tools-to-monitor-linux-performance/

SocketCluster gives you the PID for all worker and store processes on startup, so you can watch for these when using a command like ```top```.

Also, there may be node.js modules that you can bind to your worker processes from inside your actual code and will let you track various metrics.

There **may** be plans to integrate with PM2 in the future but don't count on it yet.

**Comment by IngwiePhoenix** [comment]
And what about gathering current stats? When talking about monitoring, I am thinking about stuff like the amount of requests in a specific timeframe, amount of connected clients, etc. etc.
Would there be a way to create, or pick up, such stats?

**Comment by happilymarrieddad** [comment]
You can also use htop which I find to be more useful. Another option is to use a small nodejs process to monitor CPU and memory usage using require('os'). If you are careful with how you write it, it will use less resources and you can get better metrics. You can write them to a file also if you need long term monitoring.

**Comment by jondubois** [comment]
If you're running SCC on Kubernetes, this will be supported automatically. https://github.com/SocketCluster/socketcluster/tree/master/kubernetes

I've done some tests using Rancher and the Rancher control panel lets you see how much CPU any Docker container is using. I will add more docs about this in the future.
