### ISSUE TITLE
Balancing pub-sub 

### ISSUE THREAD

**Issue by bicho** [SocketCluster/socketcluster#78]
Hi

I have HAProxy with  3 servers runing socketcluster 2.4.6 (expressjs 4), documentation says C2 do not need sticky load balancer but in tests mesagges do not reach all clients... How to configure C2 to work ok? What does the "useSmartBalancing: true" parameter?

...
new SocketCluster({
        balancers: 1,
        workers: 20,
        stores: 1,
        host: '0.0.0.0',
        port: 8000,
        appName: test,
        workerController: __dirname + "/app.js",
        balancerController: __dirname + "/balancer.js",
        storeController: __dirname + "/store.js",
        addressSocketLimit: 0,
        socketChannelLimit: 100
    })

Regards.

**Comment by jondubois** [comment]
@bicho The problem is not load balancers. They do not have to be sticky.
The problem is that you want to share channels between multiple remote SC instances.

To do this, you need to hook them up to a backend pub/sub system or message queue like Redis or RabbitMQ. See Redis example: https://github.com/socketcluster/sc-redis
Check out the guide: http://socketcluster.io/#!/docs/scaling-horizontally

**Comment by bicho** [comment]
@jondubois tested with "sc-redis"... Everything works perfect! Thx for the reply.
