### ISSUE TITLE
The efficient way to subscribe multiple channels.

### ISSUE THREAD

**Issue by bamoo456** [SocketCluster/socketcluster#81]
HI,
I just curious that does socketCluster support  subscribe multiple channels at the same time ?
or any efficient way to do this ?

> In my case,
Any clients need to subscribe multiple channels after client initialized.
so that may get some overhead if client has lots of channels need to subscribe while in initialization.

Do you have any idea on this kind of situation? 
Thanks, and very appreciate your works.

**Comment by jondubois** [comment]
@bamoo456 You can have any number of channels you like :) 
SC has a default upper limit of 1000 per socket which should be plenty. You can change the upper limit using the ```socketChannelLimit``` boot options here: http://socketcluster.io/#!/docs/api-socketcluster

You can subscribe to channels at any time (even if the socket has gone offline) - In this case, the channels will be put in a 'pending' state.

As soon the socket reconnects, any channel which was 'pending' will automatically be subscribed to the server and once this is done, their states will change to 'subscribed'.

Regarding efficiency, SC will use 1 WebSocket frame for each subscription. WebSocket frames are very lightweight so even if you did try to establish 1000 subscriptions at the same time, a single worker process should be able to handle that without too much trouble (provided that you don't have too many sockets subscribing at the exact same time - That's part of the reason why the reconnect delay is randomized with exponential backoff).

You probably don't want to have 1000 subscriptions per socket though, for security reasons, you may want to make the ```socketChannelLimit``` lower and try to unsubscribe to old channels that you no longer need.

One useful thing to do is to have one channel for each 'REST' endpoint in your app - So you can update your front-end data whenever your backend data changes. You can checkout the sample app I'm building to see how this can be done (still work in progress, but it's close to ready): https://github.com/socketcluster/sc-sample-inventory

I will try to publish the Polymer sc-socket and sc-model components independently when this is finished. Polymer components are really cool because when you remove an sc-model tag from the DOM, the related SC channel will automatically be unsubscribed.

**Comment by bamoo456** [comment]
Thanks for your detail response, that's really great on such a lightweight design of subscription request.
It truly helps me a lot :)

The `<sc-socket>` and `<sc-model>` looks interesting, it seems that this new feature can get useful when bind to `react.js` component. (when `componentWillUmount` the channel start `unsubscribe` channel.)

Awesome works and Thanks again :+1:
