### ISSUE TITLE
Sharing data between workers

### ISSUE THREAD

**Issue by IngwiePhoenix** [SocketCluster/socketcluster#82]
To be honest, the first time I read the word "store", I thought of a data store. And seeing as it's only purpose seems to be the synchronization of maschines, it kinda feels like a wrong word. However, the word store also made me think of a data store. And this is what popepd up in my mind:

```javascript
worker.getData("mykey", function(err, result){
    // ...
});
worker.setData("mykey", {foo:"bar"}, function(err){ if(err) do_something(err); });
```

That would be very convenient. For instance, I have re-worked a PHP middleware. And now I would like to be able to pre-fetch some data to avoid extranous DB usage, or to pick up cached data. So I changed my implementation to a middleware based process - and this is what I imagine would be pretty do-able:

```javascript
php.use("request", function(ctx,next){
    var routeInfo = parseRoute(ctx.req.url);
    if(routeInfo.controller == "someController") {
        if(err) next(); // Not found or not obtain-able.
        sc.getData("someController.cache."+routeInfo.id, function(err, res){
            ctx.args.cached = res; // Insert cached data. args is serialized and passed to PHP.
            next();
        });
    } else next();
});
```

This would be pretty damn cool. Imagine that you could cache a heavy-lifting SQL query's result that you could foresee from an URL and pass the cached object right in, avoiding extra lookups.

But there is more that could be do-able with being able to intercommunicate between Worker and Store.

- Share application states
- Cache content and retrive it later
- Conditionally do something, depending on the value stored.

These are just some ideas I had. Maybe they're useful, maybe not. Up to you! :)

**Comment by jondubois** [comment]
@IngwiePhoenix They actually act as both 'stores' and 'message brokers' - I've considered renaming them to brokers, but it's not completely accurate either because you can in fact store data inside them. Feel free to use that feature.

Redis is often referred to as a 'store' even though it also provides pub/sub features - Because of this, I decided to keep the word 'store' - You can think of them as 'stores for holding and managing channel subscriptions'.

SC stores are nData servers: https://github.com/socketcluster/ndata - nData is heavily inspired by Redis but it runs entirely in Node.js (the other main difference is that it lets you store deep, hierarchical/document data). I was in fact considering using Redis to make the clustering engine (https://github.com/SocketCluster/iocluster) of SC initially, but I wanted to be able to bundle everything in one package without relying on external dependencies and configurations.

The downside with nData is that it doesn't currently allow you to easily persist data to disk - So it's only meant for volatile in-memory data - It's perfectly OK to use Redis (or any other Database) alongside nData. You can access the nData stores though the ```scServer.global``` object (see http://socketcluster.io/#!/docs/api-global) - The Global object actually represents a cluster or nData clients so you can interact with multiple stores at once.

**Comment by IngwiePhoenix** [comment]
Hey.

Thanks for the infos! I was reading about nData just recently while I was exploring the SocketCluster organization - after all, SC is a vital part of my application in many ways. And thanks to your input, it just got one more task.

Considering that the cache is not persistent, I am working on a project on my own called FeatherWeight. It leverages the hprose protocol to enable cross-language communication. That way I could let the SC store run as it already is, but also access it through other services. Due to something I coded, I can pass NodeJS data into my PHP backend, allowing me to pass the current port or socket path easily.

FeatherWeight stores it’s cached data on disk when it goes down - it will listen to several „shut down“ events to archieve this. When it is launched, it will restore it’s memory from the cache.

I could see nData doing something similar. :) When I progress in FeatherWeight, you can freely re-use some of my code. The current placeholder is hosted here: https://github.com/DragonsInn/FeatherWeight <https://github.com/DragonsInn/FeatherWeight> . 

And just a heads-up: SC is amazing =)

**Comment by jondubois** [comment]
@IngwiePhoenix Thanks for the feedback. I renamed 'store' to 'broker' throughout SC as you suggested. Hopefully it makes more sense also that way developers won't feel weird about using their own databases/datastores with SC - We want to encourage that.
