### ISSUE TITLE
Sending message with scServer.global.publish, is this a leak?

### ISSUE THREAD

**Issue by 1manStartup** [SocketCluster/socketcluster#93]
Hello so I was doing some tests to send a message from client to client (User1 to User2) seeing if messages route to correct DOM.
So i put on remote server http://remoteserver:8000/user/1 and http://remoteserver:8000/user/2 and tested from my local machine by opening a tab for both /user/1 and /user/2, I sent from User1 a socket.emit('ping') it was received on server and then did from server:

scServer.global.publish('User2', 'A message from User1 to User2');

On the /user/2 page I did the following when i loaded the page:

var UserChannel = socket.subscribe('User2');

UserChannel.watch(function (count) {
  console.log('Client received data');
});

So the first test I sent a message every millisecond from User1 to User2 and although minimal, there was some load on my memory and network history incoming data. So this was expected.

But, then for my 2nd test instead of sending message from user1 to user2, I sent it to user3 which should be on the url /user/3. I did not open the /user/3 tab, but when I did the same test I noticed that there was still a load on  memory and network history.

I wanted to know if this is by design or if I am using SocketCluster wrong. What I am trying to achieve is that each client only gets 'server load' carrying their messages. For example I was not watching or listening for /user/3 messages on the /user/2 page, but still received the load from them.

Please let me know if this makes sense or I should be using another object like SCServer or SCChannel?

**Comment by jondubois** [comment]
@1manStartup It is by design. If you publish a message to a channel which doesn't have any subscribers, that message will still reach the broker process but it won't go any further.
There should still be some load on the worker and broker processes but it should be less than if you published to a channel which did have subscribers.

If you have multiple brokers and you publish to a particular channel from a worker, the message will be sent to one of your brokers (chosen based on a hash of the channel name) that way each broker only handles a subset of all possible channel names (to spread the load evenly between them).

Every message published has to go to a broker (the broker then decides which workers to route it to based on their active subscriptions). In practice, if you only have a single worker, we shouldn't really need to go through the broker at all (since there is only one possible worker to route back to) but right now it will go through it anyway (I haven't optimized for this case) keeping the behavior consistent regardless of the number of workers is nice, but I guess if we added a special setting like ```disableBrokers: true``` then we could optimize for the single-worker case, but I don't know whether or not it's worthwhile.
