### ISSUE TITLE
Working with channel

### ISSUE THREAD

**Issue by waltergms** [SocketCluster/socketcluster#97]
I search all over the internet to find some example of using scChannel.watchers() but cant find nothing and i cant get users from a channel... Someone could help me to archieve that?

**Comment by jondubois** [comment]
@waltergms In SC, watchers are functions which handle data which was published to a particular channel. Watchers are not users.

If you're trying to implement user presence. SC doesn't expose any methods for finding out who is listening to a particular channel - This is because there is no single correct way to implement this.
You will need to keep track of which users are subscribed to which channels by storing the 'channel => username' mappings in a database/datastore of your choice.

You can use JWT tokens to keep track of a user's sockets and channel subscriptions. You can also create special channels to notify clients when a new user joins or leaves a specific channel (or a particular group of channels). There are many different ways to implement this depending on your requirements so SC doesn't want to constrain you to any particular technique.

**Comment by jondubois** [comment]
I'm hoping that in the future, there will be open source plugins for SC which will implement various user presence strategies on the backend (e.g. maybe supporting different kinds of databases) and developers will be able to just install the one which make sense for their project.

**Comment by waltergms** [comment]
Understood... 
So im migrating from Socket.IO to SocketCluster.IO... I have all working using and array of rooms and inside each room i have a array of users, the question is... Is this arrays shared between workers? Or i have persist that list on database to make it visible for all workers? Because is i need to put it on database is easier to me do it on my soket.io system that is already working but arrays arent shared when using pm2 to make clusters...

**Comment by waltergms** [comment]
By the way, walking with the company standards, im using Sequelizer to make the ORM and database transactions...

**Comment by jondubois** [comment]
Yes, you should store that data in a database/data store - Otherwise your solution won't scale across multiple workers and that means it also won't scale between hosts.

A nice side effect of using SC is that if you can get your code working using multiple workers, it will generally also work using multiple hosts without having to change any code.

If your code scales across multiple processes and later you want to scale it horizontally across multiple hosts, it's usually just a matter of moving your database to its own machine or maybe sharding it but your code itself won't have to change. SC tries to encourage developers to think of their system as a distributed one from the beginning in order to avoid nasty surprises in the future when the time comes to scale out (if it comes to that).

**Comment by waltergms** [comment]
Thank you Jonathan, we currently have a traffic about 1k~10k users online and something about 70k connections/day, i will try to use SC with all the controll on the database and see what we got... I tell you latter.
Thanks
